# Sissejuhatus. Kulgliikumise kinemaatika[@Ainevaldkonna_undated-sr, lk 29-30]

## Füüsika meetod

### Õpitulemused

Kursuse lõpus õpilane:

1. selgitab mõisteid loodus, maailm ja vaatleja; hindab füüsika kohta teiste loodusteaduste seas ning
määratleb füüsika uurimisala (1-1);

2. määratleb looduse struktuuritasemete skeemil makro-, mikro- ja megamaailma ning nimetab nende
erinevusi;

3. selgitab loodusteadusliku meetodi olemust ja teab, et eksperimenditulemusi üldistades jõutakse
mudelini (1-2);

4. põhjendab mõõteseaduse vajalikkust üldaktseptitavate mõõtmistulemuste saamiseks;

5. mõistab mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevust;

6. teab ja rakendab rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid (1-4);

7. teab, et korrektne mõõtetulemus sisaldab ka määramatust, ning kasutab mõõtmisega kaasnevat
mõõtemääramatust hinnates standardhälvet (1-3);

8. toob näiteid põhjusliku seose kohta (6-5);

9. mõistab, et füüsika üldprintsiibid on kõige üldisemad tõdemused looduse kohta, ning tõestab nende
kehtivust kooskõla eksperimendiga.

1: 1-4
6: 5

### Õppesisu

1. Füüsika kui loodusteadus.

2. Füüsika kui nähtavushorisonte edasi nihutav teadus.

3. Mikro-, makro- ja
megamaailm.

4. Loodusteaduslik meetod (1-1).

5. Vaatlus, eksperiment, mudeli loomine (1-2).

6. Mudeli järelduste kontroll
ning mudeli areng (1-2).

7. Mõõtmine ja mõõtetulemus (1-3).

8. Mõõtesuurus ja mõõdetava suuruse väärtus.

9. Mõõtühikud
ja vastavate kokkulepete areng (1-4).

10. Rahvusvaheline mõõtühikute süsteem (SI) (1-4). 

11. Mõõteriistad ja mõõtevahendid (1-3).

12. Mõõteseadus. 

13. Mõõtemääramatus ning selle hindamine (1-3).

14. Mõõtetulemuste analüüs (1-7).

15. Põhjuslikkus ja juhuslikkus füüsikas (6-5).

16. Füüsika tunnetuslik ja ennustuslik väärtus.

17. Füüsikaga seotud ohud (26-6).

18. Üldprintsiibid.

1
6: 5
26: 6

### Põhimõisted

mõõtühik
: füüsikalise suuruse konkreetne väärtus, mida kokkuleppeliselt kasutatakse sama suuruse teiste väärtuste  arvuliseks iseloomustamiseks[@fsikalised]

mõõtühikute süsteem
: kokkulepitud põhiühikute ning neist tuletatud ülejäänud mõõtühikute moodustatud kogum[@erinevad]

taatlemine
: protseduur, mille käigus pädev taatluslabor või teavitatud asutus kontrollib mõõtevahendi vastavust kehtestatud nõuetele ja märgistab nõuetele vastavaks tunnistatud mõõtevahendi taatlusmärgisega[@mtevahendite]

loodus (1-2)
: inimest ümbritsev ja inimesest sõltumatult eksisteeriv keskkond[@ebook_changing_movement]

loodusteadus (1-1)
: teadus, mis annab loodusnähtustele teaduslikke kirjeldusi ja seletusi ning ennustab loodusnähtusi[@ebook_changing_movement]

füüsika (1-1)
: loodusteadus, mis eelistatult täppisteaduslike meetoditega uurib loodust ja tekitab looduse kõige üldisemad mudelid[@ebook_changing_movement]

mõõtevahend (1-3)
: tehniline vahend, mida kasutatakse mõõtmiseks kas üksi või koos lisaseadmetega[@ebook_changing_movement]

nähtavushorisont
: piir, kuni milleni on vaatlejal või inimkonnal tervikuna olemas eksperimentaalselt kontrollitud teadmised füüsikaliste objektide kohta[@ebook_changing_movement]

makromaailm
: maailm, mille moodustavad inimesest mõõtmete poolest mitte väga palju erinevad objektid[@ebook_changing_movement]

mikromaailm
: maailm, mille moodustavad inimesest mõõtmete poolest palju väiksemad objektid tüüpilise mõõtmega, mis jääb alla ühe mikromeetri (miljondiku meetri)[@ebook_changing_movement]

megamaailm
: maailm, mille moodustavad inimesest mõõtmete poolest palju suuremad objektid tüüpilise mõõtmega, mis on üle ühe megameetri (miljoni meetri ehk 1000 km)[@ebook_changing_movement]

vaatlus
: meelelise info kogumine loodusobjekti omaduste kohta objekti mõjutamata, protsessidesse sekkumata[@ebook_changing_movement]

hüpotees
: katselist kontrollimist vajav teaduslikult põhjendatud oletus[@ebook_changing_movement]

eksperiment
: looduse objekti eesmärgipärane mõjutamine või uuritava loodusnähtuse kunstlik esilekutsumine kontrollitavates tingimustes, mõõtmine (1-1, 1-3)[@ebook_changing_movement]

mõõtemääramatus (1-3)
: suurus, mis kuulub mõõtetulemuse juurde ja iseloomustab tõenäosuslikult mõõtesuuruse võimalike väärtuste vahemikku[@ebook_changing_movement]

mõõtesuurus
: nähtuse, keha või aine oluline omadus, mida saab teistest omadustest eristada ja arvuliselt kirjeldada[@ebook_changing_movement]

mõõdetava suuruse väärtus
: konkreetse suuruse arvuline määrang, mida väljendatakse arvväärtuse ehk mõõtarvu ja mõõtühiku korrutisena[@ebook_changing_movement]

mõõtetulemus
: mõõtmise teel saadud mõõtesuuruse väärtus[@ebook_changing_movement]

1: 1-4

1
6: 5
26: 6

### Praktiline tegevus ning teabe- ja suhtlustehnoloogia kasutamine

1. juhusliku loomuga nähtuse (palli põrke, heitkeha liikumise, kaldpinnalt libisemise vms) uurimine koos
mõõtmistulemuste analüüsiga (1: 3-7); 
2. keha joonmõõtmete mõõtmine ja korrektse mõõtetulemuse esitamine (1: 3-7);
3. mõõtmisest ning andmetöötlusest mudelini jõudmine erinevate katsete põhjal (1: 2-7).

1
6: 5
26: 6

## Kulgliikumise kinemaatika

### Õpitulemused

Kursuse lõpus õpilane:

1. mõistab, et füüsikalised suurused pikkus (ka teepikkus), ajavahemik (∆t) ja ajahetk (t) põhinevad
kehade ning nende liikumise (protsesside) omavahelisel võrdlemisel (2-1);

2. teab, et keha liikumisolekut iseloomustab kiirus, ning toob näiteid liikumise suhtelisuse kohta
makromaailmas (2-2, 2-3);

3. teab relativistliku füüsika peamist erinevust klassikalisest füüsikast;

4. teab, et väli liigub aine suhtes alati suurima võimaliku kiiruse ehk absoluutkiirusega;

5. eristab skalaarseid ja vektoriaalseid suurusi ning toob nende kohta näiteid (3-1);

6. seletab füüsika valemites esineva miinusmärgi tähendust (suuna muutumine esialgsele
vastupidiseks) (3-2);

7. eristab nähtuste ühtlane sirgjooneline liikumine, ühtlaselt kiirenev sirgjooneline liikumine, ühtlaselt
aeglustuv sirgjooneline liikumine ja vaba langemine olulisi tunnuseid ning toob sellekohaseid näiteid (2-5, 2-7);

8. selgitab füüsikaliste suuruste kiirus, kiirendus, teepikkus ja nihe tähendusi ning nende suuruste
mõõtmise või määramise viise (2-2, 2-3);

9. lahendab probleemülesandeid, rakendades keskmise kiiruse ja kiirenduse definitsioone \@ref(eq:velocity) leheküljel `r render_pageref(reference="eq:velocity")` ja \@ref(eq:a) leheküljel `r render_pageref(reference="eq:a")` (2: 2-6); kasutab ühtlase
sirgjoonelise liikumise ja ühtlaselt muutuva liikumise kirjeldamiseks liikumisvõrrandeid vahemaa pikkuse kohta püsiva kiiruse ja püsiva kiirenduse kaudu (2-5, 2-6);

10. analüüsib ühtlase ja ühtlaselt muutuva sirgjoonelise liikumise kiiruse ning teepikkuse graafikuid;
oskab leida teepikkust kui kiiruse graafiku alust pindala (2: 2-4, 6);

11. rakendab ühtlaselt muutuva sirgjoonelise liikumise, sh vaba langemise kiiruse, nihke ja kiirenduse
leidmiseks järgmisi seoseid: \@ref(eq:speed-by-jerk) leheküljel `r render_pageref(reference="eq:speed-by-jerk")`, \@ref(eq:path-length-by-jerk) leheküljel `r render_pageref(reference="eq:path-length-by-jerk")` ja (2: 5-7).

2
3: 1-2

1
2
3: 1-2
6: 5
26: 6

### Õppesisu

Punktmass kui keha mudel. Koordinaadid (2-1, 3-8). Taustsüsteem, liikumise suhtelisus (2-1). Relatiivsusprintsiip. Teepikkus
ja nihe (2-1). Ühtlane sirgjooneline liikumine ja ühtlaselt muutuv sirgjooneline liikumine: kiirus, kiirendus,
liikumisvõrrand, kiiruse ja läbitud teepikkuse sõltuvus ajast, vastavad graafikud (2: 2-5). Nihe, kiirus ja kiirendus kui
vektoriaalsed suurused (3-6). Vaba langemine kui näide ühtlaselt kiireneva liikumise kohta (2-7). Vaba langemise
kiirendus (2-7). Kiiruse ja kõrguse sõltuvus ajast vertikaalsel liikumisel (2-7). Erisihiliste liikumiste sõltumatus (3-4).

2: 1, 5, 7
3: 4-9

1
2
3
6: 5
26: 6

### Põhimõisted

pikkus (2-1), kulgliikumine (2, 3),
punktmass

füüsikaline suurus
: füüsikalise objekti mõõdetav iseloomustaja[@fsikaline, lk 5]

skalaarne suurus
: füüsikaline suurus, mis on esitatav vaid ühe mõõtarvu ja mõõtühikuga[@epik]

vektoriaalne suurus
: füüsikaline suurus, mis koosneb nii skalaarsest suurusest kui suunast[@physics, lk 22]

liikumisolek
: keha omadus, mis seisneb keha asukoha, asendi või kuju muutumises mingi teise keha ehk taustkeha suhtes[@epik]

aeg
: vaatleja kujutlus, mis tekitatakse liikumiste omavahelisel võrdlemisel[@epik]

taustsüsteem
: taustkeha, sellega seotud koordinaadistik ja ajamõõtmise süsteem[@epik]

kinemaatika
: sihitiste liikumise kirjeldamine[@physics, lk 20]

teepikkus
: alg- ja lõppasukoha vahekaugus täpselt piki trajektoori[@epik]

nihe
: sihitise asukoha muutus[@physics, lk 22]
(2-1)

keskmine kiirus
: jagatud selle vahemaa läbimiseks kuluva ajaga[@physics, lk 22]

hetkkiirus
: keskmine kiirus lõpmatult lühikese ajavahemiku kestel[@physics, lk 24]

kiirendus
: kiiruse muutumise kiirust väljendav suurus (2: 4, 5, 8)

vaba
langemine (2-7)
: kehade kukkumine, kus õhutakistus puudub või on väike[@ebook]

2
3

1
2
3
6: 5
26: 6

### Praktiline tegevus

1. Kiiruse ja kiirenduse mõõtmine (2: 2-8);
2. langevate kehade liikumise uurimine (2-7);
3. kaldrennis veereva kuuli liikumise uurimine (2: 4-7);
4. heitkeha liikumise uurimine (2-7). 

2: 2-8

1
2
3
6: 5
26: 6

[]{#problems}

## Ülesanded

### Mõõtmine

#### Olulised numbrid[@physics(lk 16)]

1. Mitu olulist numbrit on igal järgmistel numbritel:
 - \num{777},
 - \num{81,60},
 - \num{7,03},
 - \num{0,03},
 - \num{0,0086},
 - \num{6465} ja
 - \num{8700}?
3. Kirjutage järgmised arvud täispikkuses õige arvu nullidega:
 - \num{8,69e5},
 - \num{9,1e3},
 - \num{2,5e-1},
 - \num{4,76e2} ja
 - \num{3,62e-5}.
5. Füüsilise stopperiga mõõdetud ajavahemike määramatus on tavaliselt umbes \qty{0,2}{\s}, mis on tingitud inimese reaktsiooniajast stardi- ja peatumishetkedel. Kui suur on käsitsi ajastatud mõõtmise määramatuse protsent järgmiste ajavahemike puhul:
 - \qty{4,5}{\s},
 - \qty{45}{\s},
 - \qty{4,5}{\min}?
7. Korrutage \qty{4,079e2}{\m} \qty{0,057e-1}{\m}'ga, võttes arvesse olulisi numbreid.

9\. Väikeste nurkade $u$ korral on $\mathrm{sin}(u)$ arvväärtus ligikaudu sama, mis $\mathrm{tan}(u)$ arvväärtus.
Leia suurim nurk, mille puhul siinus ja tangens langevad kokku kahe tüvenumbri piires.

11\. Kellatootja väidab, et tema kellad ei võta juurde ega kaota aastaga rohkem kui \qty{9}{\s}. Kui täpsed need kellad protsentides on?

13\. Kui suur on ligikaudu sfäärilise rannapalli ruumala määramatuse protsent, mille raadius on $r = \qty{0,64(4)}{\m}$?

#### Ühikud, SI[@physics(lk 17)]

15. Väljendage järgmist, kasutades [eesliiteid](#prefixes):
 - \qty{3e6}{\volt},
 - \qty{2e6}{\m},
 - \num{5e3} päeva,
 - \num{18e2} taala ja
 - \qty{9e-7}{\s}.
17. Tähendusnumbrite õige arvu saamiseks kasutage nt @haynes_2014_crc's olevat teavet, et määrata
 - Maa pindala ja Kuu pindala suhe,
 - Maa ruumala võrreldes Kuu mahuga.
19. Arvatakse, et universumi vanus on umbes 14 miljardit aastat. Eeldades kahte olulist numbrit, kirjutage see kümne astmetes
 - aastas,
 - sekundis.
21. Väljendage õige tüvenumbrite arvuga järgmine summa: $\qty{1,90}{\m} + \qty{142,5}{\centi\m} + \qty{6,27e5}{\micro\m}$.

23\. Määrake teisendustegur:

 - $\frac{\unit{\kilo\m}}{\unit{\hour}} \ce{->} \frac{\text{miil}}{\unit{\hour}}$,
 - $\frac{\unit{m}}{\unit{\s}} \ce{->} \frac{\text{jalg}}{\unit{\s}}$ ning
 - $\frac{\unit{\kilo\m}}{\unit{\hour}} \ce{->} \frac{\unit{m}}{\unit{\s}}$.
[]{#tasks-intro-units-25}

25. Valgusaasta on vahemaa, mille valgus läbib ühe aasta kestel (kiirusel = \qty{2,998e8}{\m\per\s}).
 - Mitu meetrit on \num{1,00}'s valgusaastas?
 - Astronoomiline ühik (AU) on keskmine kaugus Päikesest Maani, \qty{1,50e8}{\kilo\m}. Kui palju AU'sid on \num{1,00}'s valgusaastas?
27. Mitu lainepikkust oranži krüptoon-86 valgust[@bureau_1974_the] mahuks  @physics ühe lehekülje paksusesse?

29\. Reisilennuk kulutab umbes \qty{12}{\l} kütust ühe lennukilomeetri kohta. Mis on see väärtus väljendatuna miilides galloni kohta?

31\. Arvuta:

 - Mitu sekundit on \num{1,00}'s aastas?
 - Mitu nanosekundit on \num{1,00}'s aastas?
 - Mitu aastat on \qty{1,00}{\s}'s?
33. Merkuuri läbimõõt on \qty{4879}{\kilo\m}.
 - Kui suur on Merkuuri pindala?
 - Mitu korda suurem on Maa pindala?
 
#### Suurusjärk[@physics(lk 17-18)]

35. Hinnake suurusjärku (\num{10} aste):
 - \num{3200},
 - \num{86,30e3},
 - \num{0,076} ja
 - \num{15,0e8}.
37. Hinnake, mitu tundi kuluks jooksmiseks (\qty{10}{\kilo\m\per\hour}) läbi USA New Yorgist Californiasse.
    
39\. Hinnake rakkude arvu täiskasvanud inimese kehas, arvestades, et tüüpilise raku läbimõõt on umbes \qty{10}{\milli\m} ja inimkeha tihedus umbes \qty{1000}{\kg\per\m\cubed}.

41\. Hinnake kõigi USA autojuhtide poolt aastas tarbitud bensiini gallonite arvu.

43\. Hinnake, mitu kilogrammi pesuseepi kasutatakse USA-s ühe aasta jooksul (ja seepärast pumbatakse see koos musta veega pesumasinatest välja). Oletame, et igale pesukogusele kulub \qty{0,1}{\kg} seepi.

45\. Matkarada on \qty{270}{\kilo\m} pikkune läbi erineva maastiku.
Ränd matkajaid läbib esimesed \qty{49}{\kilo\m} kahe ja poole päevaga. Hinnake, kui palju aega nad ülejäänud reisi jaoks jätavad.

47\. Hinnake tarretisubade arvu @physics(lk 17) joonisel 1-13 kujutatud purgis.

49\. Olete kuumaõhupallis, \qty{300}{\m} kõrgusel Texase tasasest tasandikust. Sa vaatad silmapiiri poole. Kui kaugele sa näed: see tähendab, kui kaugel on sinu silmapiir? Maa oma
raadius on umbes \qty{6400}{\kilo\m}.

51\. Rehvidest kulunud kumm satub enamasti atmosfääri tahkete osakeste reostusena. Hinnake, kui palju kummi (kg) Ameerika Ühendriikides aastas õhku lastakse. Alustuseks on hea hinnanguline rehvimustri sügavus uuena \qty{1}{\centi\m} ja kummi mass on umbes \qty{1200}{\kg\per\m\cubed}.

53\. Lamad rannas, silmad \qty{20}{\centi\m} kõrgusel liivast. Just siis, kui Päike loojub, täielikult horisondi taha kadudes, hüppate kohe üles, teie silmad on nüüd \qty{150}{\centi\m} liiva kohal ja näete taas Päikese tippu. Kui loete sekundite arvu ($= t$ ), kuni Päike taas täielikult kaob, saate hinnata Maa raadiust. Kuid selle ülesande jaoks kasutage aja $t$ arvutamiseks teadaolevat Maa raadiust.

#### Mõõtmed[@physics(lk 18)]

55. Objekti kiirus $v$ on antud võrrandiga $v = At^3 - Bt$, kus $t$ viitab ajale.
 - Mis on $A$ ja $B$ mõõtmed?
 - Mis on konstantide $A$ ja $B$ SI ühikud?
57. Analüüsi:
 -   Näidake, et järgmine kombinatsioon kolmest
  looduse põhikonstandist - $G = \qty{6,67e-11}{\m\cubed\per\kilo\g\per\s\squared}$, $c = \qty{3,00e8}{\m\per\s}$ ja $h = \qty{6,63e-34}{\kilo\g\m\squared\per\s}$ -  moodustavad aja mõõtmetega suuruse:
    
     $$t_\text{P} = \sqrt{\frac{G \cdot h}{c^5}}.$$
    
     Seda suurust $t_\text{P}$ nimetatakse Plancki ajaks ja arvatakse, et see on kõige varasem aeg pärast universumi loomist, mil saab rakendada praegu teadaolevaid füüsikaseadusi.
 - Hinnake $t_\text{P}$ suurusjärku, kasutades nt @haynes_2014_crc.

#### Üldised probleemid[@physics(lk 18-19)]

59. Üks mool aatomeid koosneb \num{6,02e23}'st üksikust aatomist.
Kui mool aatomeid jaotuks ühtlaselt üle Maa pinna, siis mitu aatomit oleks ruutmeetri kohta?

61\. Kui kasutaksite andmete sisestamiseks ainult klaviatuuri, siis mitu aastat kuluks kõvaketta täitmiseks arvutis, mis suudab salvestada \qty{1,0}{\tera\byte} (\qty{1,0e12}{\byte}) andmeid?
Oletagem, et töönädalad on \qty{40}{\hour} ja et saate sisestada \num{150} tähemärki minutis ja üks bait on üks klaviatuuri märk.

63\. Teatud kompaktplaat (CD) sisaldab \qty{783216}{\mega\byte} digitaalset teavet. Iga bait koosneb täpselt \qty{8}{\bit}'st.
Esitamisel loeb CD-mängija CD teavet konstantse kiirusega \qty{1,4}{\mega\bit\per\s}. Mitu minutit kulub mängijal kogu CD lugemiseks?

65\. Tüüpiline täiskasvanud inimese kops sisaldab umbes 300 miljonit väikest õõnsust, mida nimetatakse alveoolideks. Hinnake ühe alveooli keskmist läbimõõtu.

67\. Torm puistab \qty{2}{\hour} jooksul \qty{5}{\kilo\m} laiusele ja \qty{7}{\kilo\m} pikkusele linnale \qty{1,0}{\centi\m} vihma. Mitu tonni ($\qty{1}{\tonne} = \qty{10e3}{\kg}$) vett langes linnale? ( \qty{1}{\centi\m\cubed} vee mass on $\qty{1}{\g} = \qty{10e-3}{\kg}.$ ) Mitu gallonit vett see oli?

69\. Noa laev pidi olema \num{300} küünart pikk ja \num{50} küünart lai,
ja \num{30} küünart kõrge. Küünar oli mõõtühik, mis võrdub inimese küünarvarre pikkusega küünarnukist pikima sõrme otsani. Väljendage Noa laeva mõõtmed meetrites ja hinnake selle mahtu ( \unit{\m\cubed} ) .

71\. Kui kõnniksite mööda üht Maa pikkusjoont põhja poole, kuni oleksite laiuskraadi muutnud \qty{1}{\arcminute} võrra (kraadi kohta on \qty{60}{\arcminute}), kui kaugele oleksite kõndinud (miilides)? See vahemaa on meremiil[@physics(lk 7)].

73\. Jim seisab laia jõe ääres ja imestab, kui lai see on. Ta märkab otse enda vastas asuval pangal suurt kivi. Seejärel kõnnib ta \num{85} sammu ülesvoolu ja otsustab, et tema ja kivi vaheline nurk, mida ta veel näeb, on nüüd nurga all
\qty{30}{\degree} allavoolu (@physics(lk 19) joon. 1-17).
Jim mõõdab oma sammu pikkuseks umbes \qty{0,8}{\m}. Hinnake jõe laiust.

75\. Hinnake San Francisco torulukkseppade arvu.

77\. Järgmine valem hindab keskmise inimese kopsumahtu $V$ (liitrites, kus $\qty{1}{\liter} = \qty{1e3}{\centi\m\cubed}$ ):

$$V = 4,1H - 0,018A - 2,7,$$
    
kus $H$ ja $A$ on vastavalt inimese pikkus (meetrites) ja vanus (aastates). Millised on selles valemis olevate arvude \num{4,1}, \num{0,018} ja \num{2,7} ühikud?
    
79\. Hiljutised astrofüüsika avastused näitavad, et vaadeldavat universumit saab modelleerida sfäärina raadiusega $R = \num{13,7e9} \text{valgusaastat} = \qty{13,0e25}{\m}$ keskmise kogumassi tihedusega umbes \qty{1e-26}{\kg\per\m\cubed}. umbes \qty{4}{\percent} kogumassist on tingitud "tavalisest" ainest (nagu prootonid, neutronid ja elektronid). Hinnake, kui palju tavalist ainet (\unit{kg}) on vaadeldavas universumis. (Valgusaasta kohta vaadake ülesannet [25](#tasks-intro-units-25)[@physics(lk 17)].)

### *1D*' kinemaatika

#### Kiirus ja kiirusvektor

1. Kui sõidate \qty{85}{\km\per\hour} mööda sirget teed ja vaatate \qty{2,0}{\s} küljele, siis kui kaugele te selle tähelepanematuse perioodi jooksul sõidate?

3\. Osake $t_1 = \qty{-2,0}{\s}$ juures on asukohas $x_1 = \qty{5,2}{\centi\m}$ ja $t_2 = \qty{3,4}{\s}$ juures on asukohas $x_2 = \qty{8,5}{\centi\m}$. Kui suur on selle keskmine kiirusvektor sellel ajavahemikul? Kas saate nende andmete põhjal arvutada selle keskmise kiiruse? Miks või miks mitte?

5\. Sõidate koolist koju stabiilselt \qty{95}{\kilo\m\per\hour} \qty{210}{\kilo\m}. Seejärel hakkab sadama vihma ja aeglustad kiirusele \qty{65}{\kilo\m\per\hour}. Jõuate koju pärast \qty{4,5}{\hour} sõitu.

 - Kui kaugel on teie kodulinn koolist?
 - Mis oli teie keskmine kiirus?
7. Inimene jookseb \num{400}-\unit{\m} rajal kaheksa täisringi kokku \qty{14,5}{\minute}. Arvutage
 - keskmine kiirus ja
 - keskmine kiirusvektor
 \unit{\m\per\s}.
9. Sõiduauto, mis sõidab \qty{95}{\kilo\m\per\hour}, on \qty{310}{\m} taga veoautost, mis sõidab \qty{75}{\kilo\m\per\hour}. Kui kaua kulub autol veokini jõudmiseks?

11\. Kaks vedurit lähenevad üksteisele paralleelsetel rööbasteedel. Kõigi kiirus maapinna suhtes on \qty{155}{\kilo\m\per\hour}. Kui nad on esialgu üksteisest \qty{9,5}{\kilo\m} kaugusel, siis kui kaua läheb aega, enne kui nad üksteiseni jõuavad? (Vt @physics(lk 47) joon. 2-39.)

13\. Väikese objekti asukoht on antud funktsiooniga $x = \num{27} + \num{10} t \num{-2} t^3$, kus $t$ on sekundites ja $x$ meetrites.

 - Joonistage $x(t)$ funktsioonina vahemikus $t = \num{0}$ kuni $t = \qty{3,0}{\s}$.
 - Leidke objekti keskmine kiirus vahemikus \qtyrange{0}{3,0}{\s}.
 - Mis ajavahemikus \qtyrange{0}{3,0}{\s} on hetkekiirus null?

15. Kaks laeva peavad korraga jõudma keset ookeani asuvasse kohta. Nad alustavad samal ajal saabumiskohast võrdselt kaugel asuvatest positsioonidest. Nad liiguvad erineva kiirusega, kuid mõlemad liiguvad sirgjooneliselt.
Esimene laev sõidab esimese \qty{600}{\kilo\m} keskmise kiirusega \qty{20}{\kilo\m\per\hour}, järgmised \qty{800}{\kilo\m} \qty{40}{\kilo\m\per\hour},
ja \qty{20}{\kilo\m\per\hour} viimase \qty{600}{\kilo\m} jaoks. Teine laev saab sõita ainult konstantse kiirusega. Mis on selle kiiruse suurus?

17\. @physics(lk 48) joonisel 2-40

 - milliste ajavahemike jooksul (kui üldse) on kiirus konstantne?
 - mis ajal on kiirus suurim?
 - mis kell on kiirus null, kui üldse?
 - kas objekt liigub näidatud aja jooksul ühes suunas või mõlemas suunas?

19. Pideva kiirusega liikuv keeglipall tabab \qty{16,5}{\m} pikkuse keegliraja lõpus olevaid kurikaid. Pallur kuuleb palli kurikaid tabava heli \qty{2,75}{\s} pärast palli kätest vabastamist. Kui suur on kuuli kiirus, kui helikiirus on \qty{340}{\m\per\s}?

#### Kiirendus

21. Sprinter kiirendab puhkeolekust kuni kiiruseni \qty{9,00}{\m\per\s} \qty{1,48}{\s}.
Kui suur on tema kiirendus
 - \unit{\m\per\s\squared};
 - \unit{\kilo\m\per\hour\squared}?
 
23. Püsikiirusel liikuv sportauto läbib \qty{120}{\m} \qty{5,0}{\s}. Kui see seejärel pidurdab ja peatub \qty{3,7}{\s} pärast, siis kui suur on selle kiirenduse suurus (oletatav konstantne) ühikutes \unit{\m\per\s\squared} ja $g$-des ($g = \qty{9,80}{\m\per\s\squared}$)?

25\. Sirgjoonel liikuv auto alustab liikumist kohast $x = \num{0}$, kui $t_0 = \num{0}$. See auto läbib punkti $x = \qty{25,0}{\m}$ kiirusega \qty{11,0}{\m\per\s}, kui $t = \qty{3,00}{\s}$. See auto läbib punkti $x = \qty{385}{\m}$ kiirusega \qty{45,0}{\m\per\s} ajaga $t = \qty{20,0}{\s}$. Arvutada
 
 - keskmine kiirus ja
 - keskmine kiirendus
vahemikus $t = \qty{3,00}{\s}$ kuni $t = \qty{20,0}{\s}$!

27. Objekti asukoha annab funktsioon $x = At + Bt^2$,
kus $x$ on meetrites ja $t$ sekundites.
 - Mis on $A$ ja $B$ ühikud?
 - Mis on kiirenduse funktsioon ajast?
 - Mis on kiirus ja kiirendus hetkes $t = \qty{6,0}{\s}$?
 - Milline on kiirus aja funktsioonina, kui $x = At + Bt^{-3}$?
29. Auto, mis sõidab \qty{25,0}{\m\per\s}, möödub teisest, puhkeasendis olevast autost. Kui autod on täpselt kõrvuti, aeglustab esimene auto konstantse määraga \qty{2,0}{\m\per\s\squared} ja teine auto hakkab samasuguse konstantse määraga kiirendama. Millal need kaks autot jälle kõrvuti on?

31\. Sportauto kiirendab ligikaudu nii, nagu on näidatud @physics(lk 49) kiiruse-aja graafikul 2-43. (Lühikesed lõigud kõveral tähistavad käiguvahetust käsitsi.) Hinnake auto keskmist kiirendust
 
 - teisel ja
 - neljandal käigul.
 
\onecolumn
