# Füüsika ja tehnika

## Valikkursuse lühikirjeldus

Kursus on üles ehitatud õpilasele jõukohaste füüsikalis-tehnoloogiliste probleemide lahendamisele. Õpilane
teeb konkreetse probleemiga seonduvaid põhjendatud ja kompetentseid otsuseid, arvestades probleemi
loodusteaduslikke, tehnoloogilisi, majanduslikke, sotsiaalseid ja eetilisi dimensioone. Seejuures hoitakse
tasakaalus varasemates, eelkõige füüsika, ent ka teiste loodusainete kohustuslikes kursustes omandatud
teadmiste rakendamine uutes kontekstides ning uute tehnoloogiliste teadmiste ja oskuste omandamine
lähtuvalt nüüdisaja kõrgtehnoloogia väljatöötluste füüsikalisest sisust.
Kursuse struktuur põhineb üldjuhul kolmeastmelisel mudelil:
1. probleemi tuvastamine (nt teravikmikroskoopias ilmnev vajadus teha kontrollitavaid nanoskoopilisi
manipulatsioone);
2. probleeme lahendav ja sageli uurimuslikul käsitlusviisil põhinev uute teadmiste omandamine
(piesoelektrikud ja nende omadused);
3. sobiva tehnoloogilise lahenduseni jõudmine (piesoelektrilised andurid ja täiturid).
Palju kasutatakse praktilisi töid, millega määratakse peamiselt uuritava materjali või tehnilise seadme
omadusi, kuid need võivad anda ka uusi füüsikalisi teadmisi.
Kursuse õppesisu loetelus esitatakse 15 moodulit, igaüks mahuga 3–6 õppetundi. Nende hulgast valib õpetaja
koostöös õpilastega enne selgitatud vajaduste või huvide põhjal kuni 8 moodulit. Moodulid on õppesisu
loetelus esitatud nende käsitlemise soovitatavas järjestuses. Moodulite sisu uuendatakse pidevalt kooskõlas
teaduse ja tehnoloogia arenguga ning teadmistepõhise ühiskonna vajadustega. Kui kohustusliku kursuse ja
valikkursuse õppesisus on samad teemad, lisandub kohustusliku kursuse kvalitatiivkäsitlusele valikkursuses
kvantitatiivkäsitlus.

## Gümnaasiumi õppe- ja kasvatuseesmärgid

Valikkursusega taotletakse, et kursuse läbinud õpilane omandaks:
1. oma tõenäolises tulevases tehnilis-tehnoloogilises ametis kasulikke teadmisi;
2. oskuse tuvastada füüsikalis-tehnilisi probleeme tavaelus;
3. oskuse leida asjakohast ning usaldusväärset teavet meie tehnoloogilises keskkonnas ilmnevate
probleemide lahendamise kohta;
4. loodusteadusliku meetodi, sh uurimusliku käsitlusviisi kasutamise probleeme lahendades;
5. oskuse teha põhjendatud tehnilis-tehnoloogilisi otsuseid lihtsamates situatsioonides;
6. loomingulise ja kriitilisel mõtlemisel baseeruva vaate tehnoloogilistele probleemidele;
7. suulise ja kirjaliku tehnoloogilise kommunikatsiooni oskusi; 
8. loodusteaduslikke ja tehnoloogilisi teadmisi väärtustava hoiaku ning valmiduse elukestvaks õppeks;
9. oskuse hinnata tehnoloogilisi riske ning prognoosida uute tehnoloogiliste lahenduste mõju
keskkonnale. 

## Õpitulemused

Kursuse lõpus õpilane:
1. oskab leida füüsikalis-tehnoloogilisi probleeme ja nende lahendusteid argielu situatsioonidest;
2. analüüsib ja teeb põhjendatud otsuseid valitud füüsikalis-tehnoloogilisi näidisprobleeme lahendades;
3. lõimib uued tehnoloogilised teadmised varem omandatud loodusteaduslike baasteadmistega
ühtseks tervikuks;
4. kirjeldab mingi füüsikalis-tehnoloogilise probleemi parajasti kasutuses olevat lahendust ning
analüüsib selle eeliseid ja puudusi;
5. analüüsib füüsikalis-tehnoloogiliste lahendustega kaasnevaid keskkonna- või personaalriske ja nende
riskide minimeerimise võimalusi;
6. mõistab füüsikaliste loodusteaduste ning vastavate tehnoloogiate olemust ja kohta ühiskonnas ning
suhestatust kooli loodusteaduslike õppeainetega;
7. on seesmiselt motiveeritud täiendama oma füüsikalis-tehnoloogilisi teadmisi terve elu vältel.

## Õppesisu

1.  **Aero- ja hüdrodünaamika.** Keskkonna takistusjõud (5-6)[@labor_9_keskkonnatakistuse_uurimine_vedelikesdocxpdf; @looduseuurimine]. Teised õhusõidukile mõjuvad jõud (5-6). Vedelike
voolamine torudes (13: 8-10). Inimese ja looma vereringe, diastoolne ja süstoolne vererõhk (13: 10, 12, 14, 18-8). Hüdroturbiin (29-4).

    5: 6
    13: 8-14 (ainult põhikursuses)
    18: 8 (pärast põhikursuse 18: 1-4)
    29: 4 (pärast 27.4, kui on 11-tasemel käsitletud)

2.  **Elastsuslained.** Elastse deformatsiooni energia[@a82] (8.2). Võnkumiste ja lainete
energia[@a2016_165] (14: 3, 15: 3). Võnkumiste liitumine[@hallidayresnickwalker2c, lk 550-584].
Võnkumiste spekter (40-4). Doppleri efekt helilainete korral (16: 7-9). Helitugevus (16: 1-3). Detsibell (16-3). Müra ja mürakaitse (16-5).

    8: 2 (ainult mehaanika kursuses)
    12: 5 (elastse deformatsiooni energia mõistmiseks ainult mehaanika kursuses)
    14: 3 (ainult mehaanika kursuses)
    15: 3 (ainult mehaanika kursuses)
    16* (samafoonid peale 16: 3, intensiivsus ja interferents peale 16: 6, konsonants ja dissonants kõige lõpus)
    40: 4

3. **Ebatavalised faasid ja faasisiirded.** Gaaside veeldamine. Madalate temperatuuride saamine.
Krüovedelikud ja krüogeenika. Allajahutatud ja ülekuumendatud vedelikud. Härmatumine
(sublimatsioon), aine sulamistemperatuuri sõltuvus rõhust. Süsihappelumi ja teised mitte-H2O jääd.
Lahused ja faasisiirded.

4. **Soojusmasinad ja energiamajandus.** Termodünaamika I printsiibi ilmnemine isoprotsessides.
Adiabaatiline protsess. Ideaalne soojusmasin. Soojusmasina kasutegur. Ringprotsess. Pööratavad ja
mittepööratavad protsessid. Reaalsed soojusmasinad (auruturbiin, ottomootor, diiselmootor,
stirlingmootor) ja nende kasutegurid. Energiaallikad, energia muundamine, transport ja salvestamine.

5. **Entroopia ja negentroopia.** Entroopia mõiste käsitlused. Info, energia ja aine entroopiliselt
seisukohalt. Maa ja universumi entroopia ning negentroopia. Mittetasakaalulised protsessid.
Rakendused: külmuti ja soojuspump.

6. **Kondensaator ja induktiivpool.** Plaatkondensaatori mahtuvus. Kondensaatorite ehitus ja liigid. Laetud
kondensaatori energia. Kondensaatorite kasutusnäited. Pika ja peenikese pooli induktiivsus. Vooluga
induktiivpooli energia. Ülijuhtiva mähisega elektromagnetid ja nende kasutamine.

7. **Juhid ja dielektrikud.** Dielektrikute polarisatsioon. Varjestamine. Aine dielektriline läbitavus.
Piesoelektrikud ja ferroelektrikud. Rakendused: piesoelektrilised andurid ja täiturid, elektronkaal,
kvartskell.

8. **Ainete magnetilised omadused.** Aine magnetiline läbitavus. Dia- ja paramagneetikud. Kõvad ja
pehmed ferromagneetikud. Ferromagneetiku domeenstruktuur ja hüsterees. Rakendused:
elektromagnetid ja magnetiline infosalvestus.

9. **Elektrivool vedelikes ja gaasides.** Elektrolüüs. Faraday I seadus elektrolüüsi kohta. Elektrolüüsi
rakendusnäiteid. Sõltuv ja sõltumatu gaaslahendus. Kasutusnäited.

10. **Pooljuhtelektroonika.** Juhi, pooljuhi ja mittejuhi erinevused tsooniteoorias. Pooljuhtide omajuhtivus
ja selle rakendused: termotakisti, fototakisti, pooljuht-kiirgusdetektor. Pooljuhtide legeerimine.
Elektronjuhtivus ja aukjuhtivus. pn-siire. Alaldi, fotodiood, valgusdiood, dioodmaatriks, CCD-maatriks,
pooljuhtlaser. Päikesepaneelid. Bipolaar- ja väljatransistor. Kiip, selle kasutamine analoog- ja
digitaallülitustes.

11. **Vahelduvvoolu kasutamine.** Vahelduvvoolu iseloomustavad suurused. Elektriohutus. Kaitsemaandus.
Kaitsmed. Aktiiv-, induktiiv- ja mahtuvustakistus vahelduvvooluahelas. Näivtakistus. Kogutakistus.
Ohmi seadus vahelduvvooluahela kohta.

12. **Vahelduvvoolumasinad.** Alalisvoolumootor ja -generaator. Trafo talitlus, trafode kasutamine.
Vahelduvvoolugeneraator ja asünkroonmootor. Vahelduvvoolu võimsustegur. Kolmefaasiline vool.
Elektrienergia tootmine, ülekanne ja jaotamine Eesti näitel.

13. **Elektromagnetvõnkumised ja -lained.** Võnkering. Elektromagnetlainete tekitamine.
Elektromagnetlainete skaala. Raadiolained ja nende levimine. Raadioside põhialused.
Raadiolokatsioon ja GPS. Nüüdisaegsed sidevahendid.

14. **Optilised seadmed.** Valguskiir. Valguse sirgjooneline levimine. Valguse täielik peegeldumine.
Valgusjuhid ja nende kasutamine. Optilised süsteemid (objektiiv, teleskoop, mikroskoop), nende
lahutusvõime. Polariseeritud valgus ja selle saamine. Rakendused: polaroidprillid ja
vedelkristallekraan.

15. **Fotomeetria.** Inimsilma valgustundlikkus. Valgustugevus ja valgusvoog. Valgustatus. Ruuminurk.
Ühikud: kandela, luumen ja luks. Luksmeeter. Erinevate valgusallikate valgusviljakused.

## Õppetegevus

Kasutatakse järgmisi õppemeetodeid:

1. konkreetses kontekstis vajaliku füüsikalis-tehnoloogilise info leidmine õppetekstidest ja veebist;

2. teadmiste kinnistamine interaktiivsete õppevideote ja arvutimudelitega;

3. kas reaalsuses praktiliselt või katsevahendite puudumise korral virtuaalselt tehtavad uurimistööd, et
määrata eelkõige vaatlusaluse materjali või tehnilise seadme omadused;

4. rühmatöö, et leida ja analüüsida füüsikalis-tehnoloogilisi probleeme ning otsida neile lahendusi;

5. mingi tehnoloogilise lahenduse või selle alternatiivide olemust kirjeldava ning analüüsiva essee
kirjutamine; esseede vastastikune hindamine;

6. loovust arendavad tegevused: plakati loomine, arvutiesitluste koostamine, debatid ja rollimängud,
ajurünnak;

7. Cmapi meetodi kasutamine, et teadvustada ja kinnistada vaadeldava temaatika sisemisi olemuslikke
seoseid;

8. uuenduslike projektide kavandamine. 

## Kalender

### 2023-09-08

Eesmärgid:

1. Kursuse reeglid on selged.

2. Moodulid on valitud.

Kava:

1. Miks õpilane valis just selle kursuse?

2. Tutvustus: 15'st moodulist viis või kuus, millest igaühele kuus kontaktsessiooni, pluss iseseisev tegutsemine. Igas moodulis teooria, arvutusülesanded. Kui võimalik, siis eksperiment, muidu orienteerumispunkt, plakat, essee, mäng vms. Hindamine.

3. Moodulite valimine.

4. Kui aega jääb üle, siis MathCityMapi tutvustamine[@mathcitymap]. Ei jäänud.

### 2023-09-15

**Aero- ja hüdrodünaamika.**

Keskkonna takistusjõud (5-6)[@looduseuurimine; @physics, lk 134-135].

Iseseisev ülesanne lahendamiseks enne järgmist kontaktsessiooni: @physics, lk 142 lahendada ülesanded  75, 77 ja 79! Esitan siinkohal kõikide nende ülesannete püstitused maakeeli:

75: Takistusjõud suurtele objektidele, nagu autod, lennukid ja
läbi õhu liikuv taevasukelduja avaldub ligikaudselt valemiga $F_\text{D} = -c \cdot v^2$.

(a) Selle ruutsõltuvuse jaoks *v*-st määrake valem
vertikaalselt langeva objekti lõppkiiruse $v_\mathrm{T}$ jaoks.

(b) Määrake konstandi *c* väärtus \qty{75}{\kg} massiva
taevasukelduja kohta, kelle lõppkiirus on umbes \qty{60}{\m\per\s}.

(c) Joonistage selle juhtumi - $F_\mathrm{D} \propto v^2$ -  jaoks kõver nagu joonisel *5-27b*. Kummal pool joonisel *5-27* asuvat kõverat see kõver sama lõppkiiruse korral aseteseks? Selgita miks.

77: Jalgrattur võib \qty{7,8}{\degree} mäest järsult alla sõita
\qty{9,5}{\km\per\hour}. Kui takistusjõud on võrdeline kiiruse *v* ruuduga, nii et $F_\mathrm{D} = c \cdot v^2$, arvuta

(a) konstandi *c* väärtus ja

(b) keskmine jõud, mida tuleb rakendada
selleks, et laskuda mäest \qty{25}{\km\per\hour}.

Jalgratta ja jalgratturi mass on kokku \qty{80}{\kg}. Ignoreeri muud tüüpi hõõrdumist.

79: Mootorpaat, mis sõidab kiirusega \qty{2,4}{\m\per\s}, lülitab oma mootorid välja ajahetkes $t = 0$. Kui kaugele see enne seismajäämist liigub, kui märgitakse, et \qty{3,0}{\s} pärast on paadi kiirus langenud pooleni
paadi kiiruse algset väärtust? Oletame, et vee takistusjõud on
võrdeline *v*-ga.

Näidislahendused on tahvlil[@looduseuurimine].

### 2023-09-22

**Aero- ja hüdrodünaamika.**

Keskkonna takistusjõud (5-6)[@looduseuurimine; @physics, lk 135]. *12a*: Diferentsiaalvõrrandist jätkasin näidet 5-17 ja jõudsin t avaldamisest järgmise sammuni, ent siis avastasin, et olin tõstnud b valesse kohta. Õpilased soovisid ka 15 min varem lahkuda, mistõttu lõpetasin.

**Elastsuslained**

Pikilainete matemaatiline esitus (16-2)[@physics, lk 462-463]. *12b*: Jõudsime lõpuni.

Iseseisev ülesanne lahendamiseks enne järgmist kontaktsessiooni: @physics, lk 142 lahendada ülesanne 73! Maakeeli on see ülesanne selline:

\qty{3e-5}{\kg} massiva vihmapiisa lõppkiirus on
umbes \qty{9}{\m\per\s}. Eeldades takistusjõu $F_\mathrm{D} = -b \cdot v$ olemasolu tee kindlaks konstandi *b* väärtus ja aeg, mis on 
vajalik, et see vihmapiisk alates puhkeseisundist langedes saavutaks \qty{63}{\percent}
lõppkiirusest.

Näidislahendus on tahvlil[@looduseuurimine].

### 2023-09-29

**Aero- ja hüdrodünaamika.**

Keskkonna takistusjõud (5-6)[@looduseuurimine; @physics, lk 135]. *12a*'ga jätkame uuesti diferentsiaalvõrrandist, milles asume kohe asendusvõttega integreerima.

**Elastsuslained**

1. Pikilainete matemaatiline esitus (16-2)[@physics, lk 462-463].

2. Heliintensiivus, detsibellid (16-3)[@physics, lk 464-467]. *12b*'ga alustame.

Iseseisvaks lahendamiseks enne järgmist kontaktsessiooni: @physics, lk 486 lahendada ülesanded *7*, *8* ja *9*! Maakeeli on nende ülesannete püstitused sellised:

*7*: Helilaine rõhuamplituud õhus
($\rho = \qty{1,29}{\kg\per\cubic\m}$) temperatuuril \qty{0}{\degreeCelsius} on \qty{3,0e-3}{\Pa}. Mis on
nihke amplituud, kui sagedus on

(a) \qty{250}{\Hz} ja

(b) \qty{25}{\kHz}?

*8*: Milline peab olema rõhu amplituud helilaines
õhus (\qty{0}{\degreeCelsius}), kui õhumolekulid läbivad maksimaalselt nihke, mis on võrdne hapnikumolekuli läbimõõduga,
umbes \qty{3e-10}{\m}? Oletame helilaine sageduseks

(a) \qty{75}{\Hz} ja

(b) \qty{7,5}{\kHz}.

*9*: Kirjutage avaldis, mis kirjeldab rõhu muutumist funktsioonina *x*'st ja *t*'st ülesandes *8* kirjeldatud lainete puhul.

### 2023-10-6

Iseseisvaks tegemiseks järgmise kontaktsessioonini eksperiment koos [protokolli](#eksperimendi-protokolli-koostamise-juhend) koostamisega: *Kõrv ja kuulmine*[@labor1pdf]. Näidiseks on minu protokoll[@katrin_2022_akustika, lk 11-16].

### 2023-10-13

### 2023-10-20

### 2023-11-3

### 2023-11-10

### 2023-11-17

### 2023-11-24

### 2023-12-1

### 2023-12-8

### 2023-12-15

### 2023-12-22

### 2024-1-12

### 2024-1-19

### 2024-1-26

### 2024-2-2

### 2024-2-9

### 2024-2-16

### 2024-2-23

### 2024-3-8

### 2024-3-15

### 2024-3-22

### 2024-3-29

### 2024-4-5

### 2024-4-12

### 2024-4-19

### 2024-4-26

### 2024-5-3

### 2024-5-10

### 2024-5-17

### 2024-5-24

### 2024-5-31
