# Keemia alused

## Sissejuhatus

### Õpitulemused

Kursuse lõpus õpilane:

1. valdab ettekujutust keemia ajaloolisest arengust;

2. eristab kvalitatiivset ja kvantitatiivset analüüsi ning füüsikalisi ja keemilisi uurimismeetodeid.

### Õppesisu

Keemia kui teaduse kujunemine. Füüsikalised ja keemilised uurimismeetodid keemias. Keemiaga seotud karjäärivalikud.

### Põhimõisted

keemiline analüüs, kvalitatiivne analüüs, kvantitatiivne analüüs, keemiline süntees

### Praktilised tööd ja IKT rakendamine

Õppekäik keemiaga seotud ettevõttesse, õppeasutusse vms.

## Aine ehitus

### Õpitulemused

Kursuse lõpus õpilane:
kirjeldab elektronide paiknemist aatomi välises elektronkihis (üksikud elektronid, elektronipaarid) sõltuvalt elemendi asukohast perioodilisustabelis (A-rühmade elementide korral);
selgitab A-rühmade elementide metallilisuse ja mittemetallilisuse muutumist perioodilisustabelis seoses aatomi ehituse muutumisega; 
määrab A-rühmade keemiliste elementide maksimaalseid ja minimaalseid oksüdatsiooniastmeid elemendi asukoha järgi perioodilisustabelis ning koostab elementide tüüpühendite valemeid;
selgitab tüüpiliste näidete varal kovalentse, ioonilise, metallilise ja vesiniksideme olemust;
hindab kovalentse sideme polaarsust, lähtudes sidet moodustavate elementide asukohast perioodilisustabelis;
kirjeldab ning hindab keemiliste sidemete ja molekulide vastastiktoime (ka vesiniksideme) mõju ainete omadustele.

## Õppesisu

Tänapäevane ettekujutus aatomi ehitusest. Informatsioon perioodilisustabelis ja selle tõlgendamine. Keemilise sideme liigid. Vesinikside. Molekulidevahelised jõud. Ainete füüsikaliste omaduste sõltuvus aine ehitusest. 

### Põhimõisted

aatomorbitaal, mittepolaarne kovalentne side, polaarne kovalentne side, osalaeng, vesinikside

### Praktilised tööd ja IKT rakendamine

Lihtsamate molekulide struktuuri uurimine ja võrdlemine molekulimudelite või arvutiprogrammidega.

## Miks ja kuidas toimuvad keemilised reaktsioonid 

### Õpitulemused

Kursuse lõpus õpilane:
seostab keemilist reaktsiooni aineosakeste üleminekuga püsivamasse olekusse;
selgitab keemiliste reaktsioonide soojusefekte, lähtudes keemiliste sidemete tekkimisel ja lagunemisel esinevatest energiamuutustest;
analüüsib keemilise reaktsiooni kiirust mõjutavate tegurite toimet ning selgitab keemiliste protsesside kiiruse muutmist argielus;
mõistab, et pöörduvate reaktsioonide puhul tekib vastassuunas kulgevate protsesside vahel tasakaal, ning toob sellekohaseid näiteid argielust ja tehnoloogiast.

### Õppesisu

Keemilise reaktsiooni aktiveerimisenergia, aktiivsed põrked. Ekso- ja endotermilised reaktsioonid. Keemilise reaktsiooni kiirus, seda mõjutavad tegurid. Keemiline tasakaal ja selle nihkumine (Le Chatelier’ printsiibist tutvustavalt). 

### Põhimõisted

reaktsiooni aktiveerimisenergia, reaktsiooni soojusefekt, reaktsiooni kiirus, katalüsaator, katalüüs, pöörduv reaktsioon, pöördumatu reaktsioon, keemiline tasakaal

### Praktilised tööd ja IKT rakendamine

Keemilise reaktsiooni kiirust mõjutavate tegurite toime uurimine;
keemilise reaktsiooni soojusefekti uurimine;
auto heitgaaside katalüsaatori tööpõhimõtte selgitamine internetimaterjalide põhjal;
keemilise tasakaalu nihkumise uurimine sh arvutimudeli abil.

## Lahustumisprotsess, keemilised reaktsioonid lahustes

### Õpitulemused

Kursuse lõpus õpilane:
kirjeldab lahuste teket (iooniliste ja kovalentsete ainete korral);
eristab elektrolüüte ja mitteelektrolüüte ning tugevaid ja nõrku elektrolüüte;
selgitab happe ja aluse mõistet protolüütilise teoora põhjal;
oskab arvutada molaarset kontsentratsiooni;
koostab ioonidevaheliste reaktsioonide võrrandeid (molekulaarsel ja ioonsel kujul);
hindab ning põhjendab ainete vees lahustumise korral lahuses tekkivat keskkonda.

### Õppesisu 

Ainete lahustumisprotsess. Elektrolüüdid ja mitteelektrolüüdid; tugevad ja nõrgad elektrolüüdid. Hapete ja aluste protolüütiline teooria. Molaarne kontsentratsioon (tutvustavalt). Ioonidevahelised reaktsioonid lahustes, nende kulgemise tingimused. pH. Keskkond hüdrolüüsuva soola lahuses.

### Põhimõisted

hüdraatumine, elektrolüüt, mitteelektrolüüt, tugev elektrolüüt, nõrk elektrolüüt, hape, alus, molaarne kontsentratsioon, soola hüdrolüüs

### Praktilised tööd ja IKT rakendamine

Lahustumise soojusefektide uurimine;
erinevate lahuste elektrijuhtivuse võrdlemine (pirni heleduse või Vernier’ anduriga); nõrkade ja tugevate hapete ning aluste pH ja elektrijuhtivuse võrdlemine;
ioonidevaheliste reaktsioonide toimumise uurimine;
erinevate ainete vesilahuste keskkonna (lahuste pH) uurimine;
lahuse kontsentratsiooni määramine tiitrimisel (nt vee mööduva kareduse määramine, leelise kontsentratsiooni määramine puhastusvahendis või happe kontsentratsiooni määramine akuhappes vms).

## Kalender

### 2023-09-04

### 2023-9-6

### 2023-9-11

### 2023-9-13

### 2023-9-18

### 2023-9-20

### 2023-9-25

### 2023-9-27

### 2023-10-3

### 2023-10-5

### 2023-10-10

### 2023-10-12

### 2023-10-19

### 2023-10-21

### 2023-10-31

### 2023-11-2

### 2023-11-7

### 2023-11-9

### 2023-11-14

### 2023-11-16

### 2023-11-21

### 2023-11-23

### 2023-11-28

### 2023-11-30

### 2023-12-5

### 2023-12-7

### 2023-12-12

### 2023-12-14

### 2023-12-19

### 2024-1-9

### 2024-1-11

### 2024-1-16

### 2024-1-18

### 2024-1-23

### 2024-1-25

