# Mikro- ja megamaailma füüsika[@Ainevaldkonna_undated-sr, lk 36-38]

## Aine ehituse alused

### Õpitulemused

Kursuse lõpus õpilane:

1. kirjeldab aine olekuid mikrotasandil (13-1, 17-1);

2. võrdleb reaalgaasi ja ideaalgaasi mudeleid (17: 7-10, 18-3);

3. kasutab mõisteid küllastunud aur, absoluutne niiskus, suhteline niiskus ja kastepunkt ning seostab
neid ilmastikunähtustega (18-4);

4. selgitab mõisteid pindpinevus, märgamine ja kapillaarsus looduses ning tehnoloogias toimuvate
nähtustega (13-13);

5. kirjeldab aine olekuid, kasutades õigesti mõisteid faas ja faasisiire (13-1, 17-1); 

6. seletab faasisiirdeid erinevatel rõhkudel ja temperatuuridel.

13: 1, 13
17: 1, 7-10
18: 3, 4

### Õppesisu

Aine olekud, nende sarnasused ja erinevused (13-1, 17-1). Aine olekud mikrotasemel (17-1). Molekulaarjõud. Reaalgaas (18-3). Veeaur
õhus (18-4). Õhuniiskus (18-4). Küllastunud ja küllastumata aur (18-4). Absoluutne ja suhteline niiskus, kastepunkt (18-4).
Ilmastikunähtused. Pindpinevus (13-13). Märgamine ja kapillaarsus, nende ilmnemine looduses (13-13). Faasisiirded ning
siirdesoojused (18-3, 19-5, 19-10).

13: 1, 13
17: 1
18: 3-4
19: 5, 10

13: 1, 13
17: 1, 7-10
18: 3-4
19: 5, 10

### Põhimõisted

aine olek (13-1), gaas (17: 6-10, 18), vedelik (13, 17-1), kondensaine (40: 5-11), tahkis (13-1, 40: 5-7), reaalgaas (18-3), küllastunud aur (18-4), absoluutne ja
suhteline niiskus (18-4), kastepunkt (18-4), faas ja faasisiire (13-1, 17-1)

p: 10.13, 13.11-13.12, 14.5, 29.3, 29.5
r: 13.1, 13.13, 17.1, 18.3-18.4, 19.5, 40.5

13
17: 1, 6-10
18: 3, 4
19: 5, 10
40: 5-11

### Praktiline tegevus

1. Sulamistemperatuuri määramine (19-5);

2. jahutussegude võrdlemine (19-10);

3. keemistemperatuuri sõltuvuse määramine sõltuvalt lahuse kontsentratsioonist;

4. õhuniiskuse mõõtmine (18-4);

5. pindpinevuse uurimine (13-13);

6. seebivee omaduste uurimine (13-13).

13
17: 1, 6-10
18: 3, 4
19: 5, 10
40: 5-11

## Mikromaailma füüsika

### Õpitulemused

Kursuse lõpus õpilane:

1. nimetab välis- ja sisefotoefekti olulisi tunnuseid;

2. kasutab leiulaine mõistet mikromaailma nähtusi kirjeldades;

3. kirjeldab elektronide difraktsiooni (37-7);

4. nimetab füüsikaliste suuruste paare, mille vahel valitseb määramatusseos;

5. analüüsib eriseoseenergia ja massiarvu sõltuvuse graafikut (40: 1-3);

6. teab, et massi ja energia samasust kirjeldab valem E = m c2;

7. kirjeldab tuumade lõhustumise ja sünteesi reaktsioone (42: 3-4);

8. seletab radioaktiivse dateerimise meetodi olemust ning toob näiteid selle meetodi rakendamise
kohta (41-10);

9. seletab tuumareaktorite üldist tööpõhimõtet ning analüüsib tuumaenergeetika eeliseid ja sellega
seonduvaid ohte (42: 3-4);

10. teab ioniseeriva kiirguse liike ja allikaid, analüüsib ioniseeriva kiirguse mõju elusorganismidele ning
pakub võimalusi kiirgusohu vähendamiseks (42-5).

13
17: 1, 6-10
18: 3, 4
19: 5, 10
37: 7
40
41: 10-11
42: 3-5

### Õppesisu

Välis- ja sisefotoefekt. Aatomimudelid. Osakeste leiulained. Kvantmehaanika (38-40). Elektronide difraktsioon (37-7).
Määramatusseos. Aatomi kvantarvud (37-11, 39: 1, 4, 40-4). Aatomituum. Massidefekt. Seoseenergia (40: 1, 3). Eriseoseenergia. Massi ja
energia samaväärsus. Tuumareaktsioonid (42-1). Tuumaenergeetika ja tuumarelv (42: 1, 4). Radioaktiivsus (41: 3). Poolestusaeg (41-8).
Radioaktiivne dateerimine (41-10). Ioniseerivad kiirgused ja nende toimed (42-5). Kiirguskaitse.

13
17: 1, 6-10
18: 3, 4
19: 5, 10
37: 7, 11-12
38
39
40
41: 1-3, 8-11
42: 1-5

### Põhimõisted

välis- ja sisefotoefekt, kvantarv (37: 1, 11, 38-8, 39-1, 40-4), energiatase (38-8), kvantmehaanika (38-39), määramatusseos,
eriseoseenergia, tuumaenergeetika (42), tuumarelv (42-4), radioaktiivsus (41-3), poolestusaeg (41-8), radioaktiivne dateerimine (41-10),
ioniseeriv kiirgus (42-5), kiirguskaitse

27.2-27.3, 27-12, 28.1, 28.3, 28.5-28.6, 30.2-30.3, 30.8-30.9, 30.11, 31

13
17: 1, 6-10
18: 3, 4
19: 5, 10
37: 1, 7, 11-12
38
39
40
41: 1-3, 8-11
42

### Praktiline tegevus

1) tutvumine fotoefektiga;

2) kiirgusfooni mõõtmine (42-6);

3) udukambri valmistamine. 

13
17: 1, 6-10
18: 3, 4
19: 5, 10
37: 1, 7, 11-12
38
39
40
41: 1-3, 8-11
42

## Megamaailma füüsika

### Õpitulemused

Kursuse lõpus õpilane: 

1. teab, et info maailmaruumist jõuab meieni elektromagnetlainetena; nimetab ning eristab
maapealseid ja kosmoses liikuvaid astronoomia vaatlusvahendeid;

2. võrdleb Päikesesüsteemi põhiliste koostisosade mõõtmeid ja liikumisviisi: Päike, planeedid,
kaaslased, asteroidid, väikeplaneedid, komeedid, meteoorkehad;

3. kirjeldab tähti, nende evolutsiooni ja planeedisüsteemide tekkimist (44: 1-2);

4. kirjeldab galaktikate ehitust ja evolutsiooni (44-1);

5. kirjeldab universumi tekkimist ja arengut Suure Paugu teooria põhjal (43-11).

13
17: 1, 6-10
18: 3, 4
19: 5, 10
37: 1, 7, 11-12
38
39
40
41: 1-3, 8-11
42
43: 11-12
44: 1-2

### Õppesisu

Astronoomia vaatlusvahendid ja nende areng (33-8). Tähtkujud. Maa ja Kuu perioodiline liikumine aja arvestuse
alusena. Kalender. Päikesesüsteemi koostis, ehitus ning tekkimise hüpoteesid. Päike ja teised tähed (44-1). Tähtede
evolutsioon (44-2). Galaktikad (44-1). Linnutee galaktika (44-1). Universumi struktuur. Universumi evolutsioon.

13
17: 1, 6-10
18: 3, 4
19: 5, 10
33: 8
37: 1, 7, 11-12
38
39
40
41: 1-3, 8-11
42
43: 11-12
44: 1-2

### Põhimõisted

observatoorium, teleskoop (33-8), kosmoseteleskoop, Päikesesüsteem, planeet (6-5), planeedikaaslane,
tehiskaaslane (6-4), asteroid, komeet, väikeplaneet, meteoorkeha, täht (44-1), galaktika (44-1), Linnutee (44-1), kosmoloogia (44)

5.8, 7.10, 25.4, 25.8, 31.3, 32.11, 33

6: 4, 5
13
17: 1, 6-10
18: 1-4
19: 5, 10
33: 8
37: 1, 7, 11-12
38
39
40
41: 1-3, 8-11
42
43: 11-12
44

### Praktilised tööd

1) Erinevate taevakehade vaatlemine (6-5);

2) päikesekella valmistamine. 

## Kalender Edu Valemis

### 2023-09-07

Aine faasid.

Tihedus ja erikaal.

Eesmärk: Oskus kirjeldada aine olekuid mikrotasandil.

Õppesisu: Aine olekud, nende sarnasused ja erinevused.

Põhimõisted: aine olek, gaas, vedelik.

Kava:

1. Tutvustus.

2. Ajurünnak õpitu kohta.

3. Arutelu aine faaside üle[@giancoli, lk 261, @fsikaline, lk 18-24].

4. Arutelu tiheduse ja erikaalu üle koos arvutusülesande lahendamisega[@giancoli, lk 261-262].

5. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Kui veel pole, siis soetada *A4*-vormingus ruuduline kaustik või sellised lehed ja köitja, et sinna luua konspekt. Kõik seekord ülestäheldatu sinna konspekti ümber kirjutada! Kui veel pole, siis ka soetada eri värvi füüsilised kirjutusvahendid ja geomeetriavahendid! Lugeda, vaadata ja kuulata üle kontaktsessioonis viidatud teave! Lahendada @giancoli, lk 285-286 õpikust ülesanded 1, 3, 5, 7.

### 2023-09-07

Jätkasime eelmise sessiooni tegevusi.

### 2023-09-14

Rõhk voolavates ainetes.

Atmosfäärirõhk ja manomeetriline rõhk.

Kava:

1. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesannete lahendamisega[@physics, lk 367-370].

### 2023-09-21

Kava:

1. Näidata, kuidas integratsiooni kasutada füüsikas!

2. Teeme läbi näite 13-4 uuesti[@physics, lk 369]. Akvaariumiülesande valemi tuletamiseni.

### 2023-09-21

Kava:

3. Jätkame arutelu koos analüütikaga voolavate ainete rõhu teemas[@physics, lk 370]. Poole atmosfääri kõrgust ei hakanud veel arvutama.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Lahendada @physics, lk 392 ülesanded 1, 3 ja 5!

### 2023-9-28

Kava:

3. Jätkasime arutelu koos analüütikaga voolavate ainete rõhu teemas[@physics, lk 370]. Jätkasime näitest *13-5*.

4. Arutelu atmosfäärilise ja manomeetrilise rõhu üle koos kontseptuaalse näitega[@physics, lk 371].

5. Arutelu Pascali printsiibi üle[@physics, lk 371-372].

6. Rõhu mõõtmine; mõõdikud ja baromeeter[@giancoli, lk 266-267].

9. Kõrrega joomise demonstratsioon.

Selgitasin elavhõbedasamba näiteni. Lasin neil arvutada, kui kõrge on normaalrõhul elavhõbedasammas. Nad ei jõudnud välja arvutada.

### 2023-9-28

Kava:

10. Ujuvus ja Archimedese põhimõte[@giancoli, lk 268-272]. Õpilasel tekkis küsimus, et kuidas siiski näites *13-8* ämbrid sisuga ühepalju kaaluvad ja leidsin seletuse[@a4].

Jõudsin püstitada ülesande 13-9. Jätsin iseseisvaks lahendamiseks.

### 2023-10-5

Hoopis viienda taseme õpilased õpetasid midagi ja mind juhatati sööma.

### 2023-10-5

Kava:

7. Elavhõbedaga õhurõhu mõõtmise video kogemine[@elavhbe].

8. Harku õhurõhuga tutvumine[@proweatherlive_proweatherlive].

10. Ujuvus ja Archimedese põhimõte[@giancoli, lk 268-272]. Jätkasime ülesandest *13-9*, mis jäi õpilastele iseseisvaks lahendamiseks, ja jõudsime lõpuni. Rääkisin ka Archimedese avastusest vannis.

### 2023-10-12

Kava:

1. Õpilasel tekkis küsimus, et kuidas siiski näites *13-8* ämbrid sisuga ühepalju kaaluvad ja leidsin seletuse[@a4].

2. Ujuvus ja Archimedese põhimõte[@giancoli, lk 268-272; @physics, lk 376-378]. Jätkame näitest *13-10*.

3. Liikuvad vedelikud; voolukiirus
ja järjepidevuse võrrand[@physics, lk 378-380].

4. Bernoulli võrrand[@physics, lk 380-382].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Lahendada @physics, lk 392-393 ülesanded *7*, *9*, *11*, *13*, *15*, *17*, *19*, *21*, *23* ja *25*!

### 2023-11-6

### 2023-11-13

Erirelatiivsusteooria teadmiste ja oskuste kaardistamine.

### 2023-11-20

### 2023-11-27

### 2023-12-4

### 2023-12-11

### 2023-12-18

Varase kvantteooria ja aatomi mudelite teadmiste ja oskuste kaardistamine.

### 2024-1-8

### 2024-1-15

### 2024-1-22

### 2024-1-29

### 2024-2-5

Aatomite kvantmehaanika teadmiste ja oskuste kaardistamine.

### 2024-2-12

### 2024-2-19

### 2024-3-4

### 2024-3-11

### 2024-3-18

Tuumafüüsika ja radioaktiivuse teadmiste ja oskuste kaardistamine.

### 2024-3-25

### 2024-4-1

### 2024-4-8

### 2024-4-15

### 2024-4-22

Tuumaenergia ning radiatsiooni mõju ja kasutamise teadmiste ja oskuste kaardistamine.

### 2024-4-29

### 2024-5-6

### 2024-5-13

### 2024-5-20

### 2024-5-27

Astrofüüsika ja kosmoloogia teadmiste ja oskuste kaardistamine.

## Kalender Kohila Gümnaasiumis

### 2023-09-04

Aine faasid.

Tihedus ja erikaal.

Eesmärk: Oskus kirjeldada aine olekuid mikrotasandil.

Õppesisu: Aine olekud, nende sarnasused ja erinevused.

Põhimõisted: aine olek, gaas, vedelik.

Kava:

1. Tutvustus.

2. Ajurünnak õpitu kohta.

3. Arutelu aine faaside üle[@giancoli, lk 261, @fsikaline, lk 18-24].

4. Arutelu tiheduse ja erikaalu üle koos arvutusülesande lahendamisega[@giancoli, lk 261-262]. *12a*: Selle ülesande lahendamine jäi ainult algusfaasi. *12b*: See ülesanne sai lahendatud.

7. Kokkuvõte.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Kui veel pole, siis soetada *A4*-vormingus ruuduline kaustik või sellised lehed ja köitja, et sinna luua konspekt. Kõik seekord ülestäheldatu sinna konspekti ümber kirjutada! Kui veel pole, siis ka soetada eri värvi füüsilised kirjutusvahendid ja geomeetriavahendid! Lugeda, vaadata ja kuulata üle kontaktsessioonis viidatud teave! Lahendada @giancoli, lk 285-286 õpikust ülesanded 1, 3, 5, 7.

### 2023-09-11

Kava:

1. Pindpinevuse ja kapillaarsuse õppimine näidisülesande lahendamisega[@physics, lk 386-388]. Lahend jäi kommenteerimata.

### 2023-09-18

Eesmärgid: Õpilane oskab

4. selgitada mõisteid *pindpinevus*, *märgamine* ja *kapillaarsus* looduses ning tehnoloogias toimuvate
nähtustega (13-13);

Õppesisu: Märgamine ja kapillaarsus, nende ilmnemine looduses (13-13).

Kava:

0. Pindpinevuse ja kapillaarsuse õppimine näidisülesande lahendi kommenteerimisega[@physics, lk 387-388; @elavhbe; @pindpinevus].

1. Arutelu tiheduse ja erikaalu üle koos arvutusülesande lahendamisega (*12a*)[@giancoli, lk 261-262; @physics, lk 366-367].

2. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262-263; @physics, lk 367-370]. *12b*: Tuletasin rõhu valemi tiheduse, kõrguse ja g järgi.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Lahendada ülesanded @physics, lk 392, 396'st:

0*: 73, 75, 77,

1*: 1, 3, 5.

Esitan siinkohal kõik need ülesanded maakeeles:

1: El Capitan Yosemite'i rahvuspargis oleva graniitmonoliidi ligikaudne maht on umbes \qty{1e8}{\m\cubed}  (joonis *13-51*)[@haynes_2014_crc]. Mis on selle ligikaudne mass?

3: Milline on ligikaudne õhu mass elutoas mõõtmetega
5,6 m * 4,6 m * 2,4 m[@haynes_2014_crc]?

5: Pudeli mass tühjana on \qty{32,00}{\g} ja \qty{98,44}{\g},
kui see on täidetud veega. Kui täidetakse teise vedelikuga,
on pudeli ja vedeliku mass kokku \qty{89,22}{\g}. Milline on selle teise vedeliku eritihedus?

73: Arvuta traadi voolava vedeliku pinnal hoidmiseks vajalik jõud (joonis *13-37*), kui see vedelik on seebilahus (tabel *13-4*) ja
traat on \qty{21,5}{\cm} pikk.

75: Hinda terasnõela läbimõõtu, mis jääb
pindpinevuse tõttu vaevu vee peale (joonised *13-38*, *13-39a*, tabel *13-1*)!

77: Pindpinevuse tõttu suudab vedelik kerkida kitsas torus.
Näita, et kitsas torus, mis asetatakse vedelikku tihedusega $\rho$ ja pindpinevusega $\gamma$, raadiusega *r* tõuseb edelik kõrgusele $h = \frac{2 \cdot \gamma}{g \cdot r \cdot \rho}$ vedeliku pinnast väljaspool kapillaari, kusjuures *g* on gravitatsioonist tingitud kiirendus. Eelda, et vedelik märgab toru ja et vedeliku pind on toruga risti.

\onecolumn

### 2023-09-25

Kava:

2. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262-263; @physics, lk 367-370]. *12a*: Õpilased sportisid, mina passisin. *12b*: alustame ülesandest *A*. Jõudsin valemini 13-6b.

### 2023-10-2

Kava:

2. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262-263; @physics, lk 367-370]. *12a*: alustasime algusest ja jõudsime valemini 13-4. *12b*: alustasime näitest *13-3* ja harjutuseni B tehtud.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Lahendada @physics, lk 392'st ülesanded *1*, *3*, ja *5*!

\twocolumn

### 2023-10-9

Kava:

2. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262-263; @physics, lk 367-370]. *12a*: alustasime valemi *13-5* tuletamisest. Näite *13-4* tegime läbi. Vaja veel vaid kontrollida keskmisega.
 *12b*: alustasime valemi *13-6c* tuletamisest.

3. Arutelu atmosfääri rõhu ja manomeetri rõhu üle koos arvutamise ja praktiseerimisega[@physics, lk 371; @elavhbe]. *12b*:  Jõudsime peatüki *13-4* lõpuni.

\onecolumn

### 2023-10-16

Kava:

2. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262-263; @physics, lk 367-370]. *12a*: Näite *13-4* tegime läbi. Lk 370 ülaosa käsitletud. Pillery ja Katrina lahendasid akvaariumiülesannet keskmisega.

3. Arutelu atmosfääri rõhu ja manomeetri rõhu üle koos arvutamise ja praktiseerimisega[@physics, lk 371; @elavhbe].

4. Pascali põhimõte[@giancoli, lk 265; @physics, lk 371-372]. *12b*: tegime läbi.

5. Rõhu mõõtmine; mõõdikud ja baromeeter[@giancoli, lk 266-267; @physics, lk 372-374]. *12b*: Tabeli 13-2 kirjeldasin ja arvutasin, kui suurt rõhuerinevust saab mõõta 1 mm veesambaga.

6. Harku õhurõhuga tutvumine[@proweatherlive_proweatherlive].

7. Kõrrega joomise demonstratsioon.

8. Ujuvus ja Archimedese põhimõte[@giancoli, lk 268-272; @physics, lk 374-378].

\twocolumn

### 2023-10-30

Kava:

2. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262-263; @physics, lk 367-370]. *12a*: Alustasime kõrguse mõjuga atmosfäärirõhule lk 370. Näide 13-5: arutasime, kuidas lahendada, jätan koju lahendada.

3. Arutelu atmosfääri rõhu ja manomeetri rõhu üle koos arvutamise ja praktiseerimisega[@physics, lk 371; @elavhbe].

4. Pascali põhimõte[@giancoli, lk 265; @physics, lk 371-372].

5. Rõhu mõõtmine; mõõdikud ja baromeeter[@giancoli, lk 266-267; @physics, lk 372-374]. *12b*: Jätkasime tabeli 13-2 alt. Arvutasime vedelikusamba kõrgust elavhõbedaga normaal- ja standardrõhul, samuti veega. Lõpuks proovisime e astme valemit ja tegime vea sellega, et lühem valem kehtib vedeliku sees, pikem valem väljaspool ehk oleks pidanud õhu tiheduse panema.

### 2023-11-6

Kava:

2. Arutelu voolavates ainetes oleva rõhu üle koos arvutusülesande lahendamisega[@giancoli, lk 262-263; @physics, lk 367-370]. *12a*: Kas keegi lahendas näite 13-5?

3. Arutelu atmosfääri rõhu ja manomeetri rõhu üle koos arvutamise ja praktiseerimisega[@physics, lk 371; @elavhbe].

4. Pascali põhimõte[@giancoli, lk 265; @physics, lk 371-372]. *12a*: Arvutasime, milline on rõhk 100 m sügavuses vees (lk 371 all).

5. Rõhu mõõtmine; mõõdikud ja baromeeter[@giancoli, lk 266-267; @physics, lk 372-374]. *12b*: Selgitan, et tegime vea sellega, et lühem valem kehtib vedeliku sees, pikem valem väljaspool ehk oleks pidanud õhu tiheduse panema. See on siis @physics(lk 373) allosas.

6. Harku õhurõhuga tutvumine[@proweatherlive_proweatherlive].

7. Kõrrega joomise demonstratsioon.

8. Ujuvus ja Archimedese põhimõte[@giancoli, lk 268-272; @physics, lk 374-378]. Õpilasel tekkis küsimus, et kuidas siiski näites *13-8* ämbrid sisuga ühepalju kaaluvad ja leidsin seletuse[@a4]. *12b*: Käsitlesime näite 13-8 koos selgitava videoga.

### 2023-11-13

Kava:

1. Gaasi- ja vedelikusambad (Mirjam), vedelikusamba rõhu valem (Eneli), hüdrauliline masin (Kristel)[@fsikaline(lk 21)].

4. Pascali põhimõte[@giancoli, lk 265; @physics, lk 371-372]. *12a*: Kuna arvutasime, milline on rõhk 100 m sügavuses vees (lk 371 all), siis jätkan selgitamisega, et sellele lisandub õhurõhk. Ülesanne 9, *12b*: ülesanne 11.

5. Rõhu mõõtmine; mõõdikud ja baromeeter[@giancoli, lk 266-267; @physics, lk 372-374].

6. Harku õhurõhuga tutvumine[@proweatherlive_proweatherlive].

8. Ujuvus ja Archimedese põhimõte[@giancoli, lk 268-272; @physics, lk 374-378]. Õpilasel tekkis küsimus, et kuidas siiski näites *13-8* ämbrid sisuga ühepalju kaaluvad ja leidsin seletuse[@a4]. *12b*: Jätkame näitega 13-9.

### 2023-11-20

### 2023-11-27

### 2023-12-4

### 2023-12-11

### 2023-12-18

Varase kvantteooria ja aatomi mudelite teadmiste ja oskuste kaardistamine.

### 2024-1-8

### 2024-1-15

### 2024-1-22

### 2024-1-29

### 2024-2-5

Aatomite kvantmehaanika teadmiste ja oskuste kaardistamine.

### 2024-2-12

### 2024-2-19

### 2024-3-4

### 2024-3-11

### 2024-3-18

Tuumafüüsika ja radioaktiivuse teadmiste ja oskuste kaardistamine.

### 2024-3-25

### 2024-4-1

### 2024-4-8

### 2024-4-15

### 2024-4-22

Tuumaenergia ning radiatsiooni mõju ja kasutamise teadmiste ja oskuste kaardistamine.

### 2024-4-29

### 2024-5-6

### 2024-5-13

### 2024-5-20

### 2024-5-27

Astrofüüsika ja kosmoloogia teadmiste ja oskuste kaardistamine.

## Ülesanded

### Tihedus ja eritihedus

1) El Capitan Yosemite’i rahvuspargis oleva graniitmonoliidi ligikaudne maht on umbes \qty{1e8}{\m\cubed}. Mis on selle ligikaudne mass?

3) Milline on ligikaudne õhu mass elutoas mõõtmetega $\qty{5,6}{\m} \times \qty{4,6}{\m} \times \qty{2,4}{\m}$?

5) Pudeli mass tühjana on \qty{32,00}{\g} ja \qty{98,44}{\g}, kui see on täidetud veega. Kui täidetakse teise vedelikuga, on pudeli ja vedeliku mass kokku \qty{89,22}{\g}. Milline on selle teise vedeliku eritihedus?

### Rõhk ja Pascali põhimõte

7)  Hinnake põrandale avaldatavat survet

  - ühe terava kontsa pindalaga \qty{0,45}{\centi\m\squared} ja
  
  - ühe laia kontsaga, mille pindala on \qty{18}{\centi\m\squared}.
  
    Jalatseid kandva inimese mass on \qty{56}{\kg}.

9) Arvutage $\qty{1,7}{\m} \times  \qty{2,6}{\m}$ mõõtmetega laua pealispinnale mõjuv atmosfääri kogujõud. Kui suur on kogu jõud, mis mõjub laua alumisele küljele ülespoole?

11) Kui kõrge oleks tase alkoholibaromeetris normaalsel atmosfäärirõhul?

13) Soovitatav rehvirõhk konkreetse auto jaoks on \qty{220}{\kilo\pascal}. Kui auto mass on \qty{1250}{\kg}, siis milline iga rehvi ala peab olema kokkupuutes teega? Oletame, et auto
kaal jaotub ühtlaselt kõigi \num{4} rehvi vahel.

### Pindpinevus ja kapillaarsus[@physics(lk 396)]

73) Arvutage @physics(lk 386)'i joonisel 13-37 traadi liigutamiseks vajalik jõud, kui see hoiab seebilahust (tabel 13-4 @physics(lk 387)'s) ja traadi pikkus on \qty{21,5}{\centi\m}.
