# Sissejuhatus füüsikasse. Kulgliikumise kinemaatika[@Ainevaldkonna_undated-sr, lk 29-30]

## Füüsika meetod

### Õpitulemused

Kursuse lõpus õpilane:

1. selgitab mõisteid loodus, maailm ja vaatleja; hindab füüsika kohta teiste loodusteaduste seas ning
määratleb füüsika uurimisala (1-1);

2. määratleb looduse struktuuritasemete skeemil makro-, mikro- ja megamaailma ning nimetab nende
erinevusi;

3. selgitab loodusteadusliku meetodi olemust ja teab, et eksperimenditulemusi üldistades jõutakse
mudelini (1-2);

4. põhjendab mõõteseaduse vajalikkust üldaktseptitavate mõõtmistulemuste saamiseks;

5. mõistab mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevust;

6. teab ja rakendab rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid (1-4);

7. teab, et korrektne mõõtetulemus sisaldab ka määramatust, ning kasutab mõõtmisega kaasnevat
mõõtemääramatust hinnates standardhälvet (1-3);

8. toob näiteid põhjusliku seose kohta (6-5);

9. mõistab, et füüsika üldprintsiibid on kõige üldisemad tõdemused looduse kohta, ning tõestab nende
kehtivust kooskõla eksperimendiga.

1: 1-4
6: 5

### Õppesisu

Füüsika kui loodusteadus. Füüsika kui nähtavushorisonte edasi nihutav teadus. Mikro-, makro- ja
megamaailm. Loodusteaduslik meetod (1-1). Vaatlus, eksperiment, mudeli loomine (1-2). Mudeli järelduste kontroll
ning mudeli areng (1-2). Mõõtmine ja mõõtetulemus (1-3). Mõõtesuurus ja mõõdetava suuruse väärtus. Mõõtühikud
ja vastavate kokkulepete areng (1-4). Rahvusvaheline mõõtühikute süsteem (SI) (1-4). Mõõteriistad ja mõõtevahendid (1-3).
Mõõteseadus. Mõõtemääramatus ning selle hindamine (1-3). Mõõtetulemuste analüüs (1-7).
Põhjuslikkus ja juhuslikkus füüsikas (6-5). Füüsika tunnetuslik ja ennustuslik väärtus. Füüsikaga seotud ohud (26-6).
Üldprintsiibid.

1
6: 5
26: 6

### Põhimõisted

loodus (1-2), loodusteadus (1-1), füüsika (1-1), mõõtevahend (1-3), taatlemine, nähtavushorisont, makro-, mikro- ja
megamaailm; vaatlus, hüpotees, eksperiment, mõõtmine (1-1, 1-3), mõõtühik (1-4), mõõtühikute süsteem (1-4),
mõõtemääramatus (1-3), mõõtesuurus, mõõdetava suuruse väärtus, mõõtetulemus

1: 1-4

1
6: 5
26: 6

### Praktiline tegevus ning teabe- ja suhtlustehnoloogia kasutamine

1. juhusliku loomuga nähtuse (palli põrke, heitkeha liikumise, kaldpinnalt libisemise vms) uurimine koos
mõõtmistulemuste analüüsiga (1: 3-7); 
2. keha joonmõõtmete mõõtmine ja korrektse mõõtetulemuse esitamine (1: 3-7);
3. mõõtmisest ning andmetöötlusest mudelini jõudmine erinevate katsete põhjal (1: 2-7).

1
6: 5
26: 6

## Kulgliikumise kinemaatika

### Õpitulemused

Kursuse lõpus õpilane:

1. mõistab, et füüsikalised suurused pikkus (ka teepikkus), ajavahemik (∆t) ja ajahetk (t) põhinevad
kehade ning nende liikumise (protsesside) omavahelisel võrdlemisel (2-1);

2. teab, et keha liikumisolekut iseloomustab kiirus, ning toob näiteid liikumise suhtelisuse kohta
makromaailmas (2-2, 2-3);

3. teab relativistliku füüsika peamist erinevust klassikalisest füüsikast;

4. teab, et väli liigub aine suhtes alati suurima võimaliku kiiruse ehk absoluutkiirusega;

5. eristab skalaarseid ja vektoriaalseid suurusi ning toob nende kohta näiteid (3-1);

6. seletab füüsika valemites esineva miinusmärgi tähendust (suuna muutumine esialgsele
vastupidiseks) (3-2);

7. eristab nähtuste ühtlane sirgjooneline liikumine, ühtlaselt kiirenev sirgjooneline liikumine, ühtlaselt
aeglustuv sirgjooneline liikumine ja vaba langemine olulisi tunnuseid ning toob sellekohaseid näiteid (2-5, 2-7);

8. selgitab füüsikaliste suuruste kiirus, kiirendus, teepikkus ja nihe tähendusi ning nende suuruste
mõõtmise või määramise viise (2-2, 2-3);

9. lahendab probleemülesandeid, rakendades definitsioone (2: 2-6);

10. kasutab ühtlase
sirgjoonelise liikumise ja ühtlaselt muutuva liikumise kirjeldamiseks vastavaltliikumisvõrrandeid (2-5, 2-6);

11. analüüsib ühtlase ja ühtlaselt muutuva sirgjoonelise liikumise kiiruse ning teepikkuse graafikuid;
oskab leida teepikkust kui kiiruse graafiku alust pindala (2: 2-4, 6);

12. rakendab ühtlaselt muutuva sirgjoonelise liikumise, sh vaba langemise kiiruse, nihke ja kiirenduse
leidmiseks järgmisi seoseid: (2: 5-7).

2
3: 1-2

1
2
3: 1-2
6: 5
26: 6

### Õppesisu

Punktmass kui keha mudel. Koordinaadid (2-1, 3-8). Taustsüsteem, liikumise suhtelisus (2-1). Relatiivsusprintsiip. Teepikkus
ja nihe (2-1). Ühtlane sirgjooneline liikumine ja ühtlaselt muutuv sirgjooneline liikumine: kiirus, kiirendus,
liikumisvõrrand, kiiruse ja läbitud teepikkuse sõltuvus ajast, vastavad graafikud (2: 2-5). Nihe, kiirus ja kiirendus kui
vektoriaalsed suurused (3-6). Vaba langemine kui näide ühtlaselt kiireneva liikumise kohta (2-7). Vaba langemise
kiirendus (2-7). Kiiruse ja kõrguse sõltuvus ajast vertikaalsel liikumisel (2-7). Erisihiliste liikumiste sõltumatus (3-4).

2: 1, 5, 7
3: 4-9

1
2
3
6: 5
26: 6

### Põhimõisted

füüsikaline suurus, skalaarne ja vektoriaalne suurus (3-1), pikkus (2-1), liikumisolek (2: 1-4), aeg (2-2), kulgliikumine (2, 3),
punktmass, taustsüsteem (2-1), kinemaatika (2, 3), teepikkus (2-1), nihe (2-1), keskmine kiirus (2-2), hetkkiirus (2-3), kiirendus (2: 4, 5, 8), vaba
langemine (2-7)

2
3

1
2
3
6: 5
26: 6

### Praktiline tegevus

1. Kiiruse ja kiirenduse mõõtmine (2: 2-8);
2. langevate kehade liikumise uurimine (2-7);
3. kaldrennis veereva kuuli liikumise uurimine (2: 4-7);
4. heitkeha liikumise uurimine (2-7). 

2: 2-8

1
2
3
6: 5
26: 6

## Edu Valemi Kalender

### 2023-09-05

Teaduse olemus.

Füüsika ja selle seos teiste valdkondadega.

Mudelid, teooriad ja seadused.

Eesmärgina õpilane oskab

1. selgitada mõisteid loodus, maailm ja vaatleja; hindab füüsika kohta teiste loodusteaduste seas ning
määratleb füüsika uurimisala;

2. määratleda looduse struktuuritasemete skeemil makro-, mikro- ja megamaailma ning nimetab nende
erinevusi;

3. selgitada loodusteadusliku meetodi olemust ja teab, et eksperimenditulemusi üldistades jõutakse
mudelini;

8. tuua näiteid põhjusliku seose kohta;

9. mõista, et füüsika üldprintsiibid on kõige üldisemad tõdemused looduse kohta, ning tõestada nende
kehtivust kooskõla eksperimendiga.

Õppesisu: Füüsika kui loodusteadus. Füüsika kui nähtavushorisonte edasi nihutav teadus. Mikro-, makro- ja
megamaailm. Loodusteaduslik meetod. Vaatlus, eksperiment, mudeli loomine. Mudeli järelduste kontroll
ning mudeli areng.

Kava:

1. Tutvustus.

2. Ajurünnak õpitu kohta.

3. Arutelu teaduse olemuse üle[@fsikaline, lk 3-5, @giancoli, lk 2-4].

4. Ajurünnak oma tulevikusoovide ja füüsikaseoste kohta[@giancoli, lk 4-5].

5. Arutelu mudelite, teooriate ja seaduste üle.

6. Näidete esitamine põhjusliku seose kohta[@giancoli, lk 128].

7. Füüsika üldprintsiipid ja nende kehtivuse tõestamine[@teised].

8. Kokkuvõte.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni: Kui veel pole, siis soetada *A4*-vormingus ruuduline kaustik või sellised lehed ja köitja, et sinna luua konspekt. Kõik seekord ülestäheldatu sinna konspekti ümber kirjutada! Kui veel pole, siis ka soetada eri värvi füüsilised kirjutusvahendid ja geomeetriavahendid! Lugeda, vaadata ja kuulata üle kontaktsessioonis viidatud teave!

### 2023-09-05

Mõõtmine ja määramatus; tüvenumbrid[@giancoli, lk 5-8].

Eesmärgid:

1. Oskus põhjendada mõõteseaduse vajalikkust üldaktseptitavate mõõtmistulemuste saamiseks.

2. Mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevus on selge.

7. Õpilane teab, et korrektne mõõtetulemus sisaldab ka määramatust, ning kasutab mõõtmisega kaasnevat
mõõtemääramatust hinnates standardhälvet (ilmselt käsitleme standardhälvet hiljem).

Õppesisu: Mõõtmine ja mõõtetulemus. Mõõtesuurus ja mõõdetava suuruse väärtus. Mõõteriistad ja mõõtevahendid.
Mõõteseadus (ilmselt käsitleme hiljem). Mõõtemääramatus ning selle hindamine. Mõõtetulemuste analüüs.

Põhimõiste:

füüsikaline suurus
: füüsikalise objekti mõõdetav iseloomustaja[@fsikaline, lk 5]

### 2023-9-7

Ühikud, standardid ja Système Internationale[@giancoli, lk 8-11].

Ühikute teisendamine[@giancoli, lk 11-12].

Eesmärk: Õpilane teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid.

Õppesisu: Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI).

Põhimõisted:

mõõtühik
: füüsikalise suuruse konkreetne väärtus, mida kokkuleppeliselt kasutatakse sama suuruse teiste väärtuste  arvuliseks iseloomustamiseks[@fsikalised]

mõõtühikute süsteem
: kokkulepitud põhiühikute ning neist tuletatud ülejäänud mõõtühikute moodustatud kogum[@erinevad]

Kava:

1. Teaduste piiride kirjeldamine[@looduse; @mikro].

2. *Powers of Ten - Ultimate Zoom (micro-macro - Imax combined)*[@powers; @giancoli, lk 9].

3. Mõõtühikute eesliidetega tutvumine[@mthikute; @giancoli, lk 10].

4. Harjutused mõõtühikute eesliidetega.

### 2023-09-7

Mõõtmine ja määramatus; tüvenumbrid[@giancoli, lk 5-8].

Kava:

1. Mõõtemääramatusega tutvumine[@kella; @mtetulemus; @neli; @higgsi; @a; @giancoli, lk 5-6].

2. Mõõtemääramatuse praktiliste ülesannete lahendamine.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Lahendada @giancoli, lk 18 ülesanded 1, 3, 5, 7, 9, 11, 13!

### 2023-9-7

Õpilased jätkasid teisendamisharjutuste sooritamist.

### 2023-9-12

Eesmärgina õpilane

5. mõistab mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevust;

Õppesisu: Mõõtesuurus ja mõõdetava suuruse väärtus.

Kava:

1. Ümardamine[@rounding].

2. Tüvenumbrid[@sigfigpdf; @significantfigurespdf; @physics, lk 4-6; @introduction; @rounding].

Selgitasin ümardamise ja tüvenumbrite reegleid.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni vastavalt kava teemadele, kui jõudsime selle teema läbida: lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

### 2023-9-12

Rakendasime ümardamise ja tüvenumbrite reegleid.

### 2023-09-14

Õppesisu: Mõõtesuurus ja mõõdetava suuruse väärtus. Mõõtühikud
ja vastavate kokkulepete areng.

Kava:

3. Ühikute teisendamine[@physics, lk 1, 9-10; @introduction_conversions; @haynes_2014_crc, lk 1-27-1-46; @erinevad; @mthikute; @conversions; @unit; @physics_151].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni: Lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

### 2023-09-19

Eesmärgina õpilane

4. oskab põhjendada mõõteseaduse vajalikkust üldaktseptitavate mõõtmistulemuste saamiseks;

5. mõistab mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevust;

6. teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid.

Õppesisu: Mõõtmine ja mõõtetulemus. Mõõtesuurus ja mõõdetava suuruse väärtus. Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI). Mõõteriistad ja mõõtevahendid.
Mõõteseadus.

Põhimõisted:

taatlemine
: protseduur, mille käigus pädev taatluslabor või teavitatud asutus kontrollib mõõtevahendi vastavust kehtestatud nõuetele ja märgistab nõuetele vastavaks tunnistatud mõõtevahendi taatlusmärgisega[@mtevahendite]

mõõtühikute süsteem
: kokkulepitud põhiühikud ning neist tuletatud ülejäänud mõõtühikud[@erinevad]

Kava:

4. SI[@sipostera4pdf; @physics, lk 8-9; @bureau_1974_the; @rahvusvaheline; @nistsp_1247png; @a11]. Ainult selgitasin.

### 2023-9-19

Eesmärgina õpilane

6. teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid.

Õppesisu: Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI).

Põhimõisted:

mõõtühikute süsteem
: kokkulepitud põhiühikud ning neist tuletatud ülejäänud mõõtühikud[@erinevad]

Kava:

4. SI[@sipostera4pdf; @physics, lk 8-9; @bureau_1974_the; @rahvusvaheline; @nistsp_1247png; @a11]. Õpilased lahendasid ülesandeid jõudes kolmanda plokini.

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni: Lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

### 2023-09-21

Eesmärgina õpilane

5. mõistab mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevust;

6. teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid;

7. teab, et korrektne mõõtetulemus sisaldab ka määramatust, ning oskab kasutada mõõtmisega kaasnevat
mõõtemääramatust hinnates standardhälvet.

Õppesisu: Mõõtmine ja mõõtetulemus. Mõõtesuurus ja mõõdetava suuruse väärtus. Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI). Mõõteriistad ja mõõtevahendid.
Mõõteseadus. Mõõtemääramatus ning selle hindamine. Mõõtetulemuste analüüs.

Põhimõisted:

mõõtühikute süsteem
: kokkulepitud põhiühikud ning neist tuletatud ülejäänud mõõtühikud[@erinevad]

mõõtemääramatus
: suurus, mis kuulub mõõtetulemuse juurde ja iseloomustab tõenäosuslikult mõõtesuuruse võimalike väärtuste vahemikku[@mtmise]

Kava:

4. SI[@sipostera4pdf; @physics, lk 8-9; @bureau_1974_the; @rahvusvaheline; @nistsp_1247png; @a11].

5. Dimensionaalanalüüs[@physics, lk 14-15; @introduction_base_dimensions]. SI tuletatud ühikute dimensionaalanalüüs.

6. Tabavus, täpsus, veatüübid ja määramatus[@mgpg11pdf; @physics, lk 3-4, 6; @introduction_accuracy_precision; @mtmise_precision; @a12].

7. Toores hinnang[@physics, lk 11-13].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni vastavalt kava teemadele, kui jõudsime selle teema läbida: Lahendada @physics, lk 16-18 järgmised ülesanded:

3, 4: 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,

5: 55, 57,

2, 6: 1, 3, 5, 7, 9, 11, 13,

7: 35, 37, 39, 41, 43, 45, 47, 49, 51, 53.

Lisaks lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

### 2023-09-25

Ühikud, standardid ja Système Internationale.

### 2023-09-29

Ühikute teisendamine.

### 2023-10-2

Suurusjärk: kiire hindamine.

### 2023-10-6

Mõõtmed ja mõõtmete analüüs.

### 2023-10-9

### 2023-10-13

Füüsika olemuse, mõõtmise ja hindamise teadmiste ja oskuste kaardistamine.

### 2023-10-16

### 2023-10-20

### 2023-10-30

### 2023-11-3

### 2023-11-6

### 2023-11-10

### 2023-11-13

### 2023-11-17

### 2023-11-20

### 2023-11-24

Liikumise kirjeldamise teadmiste ja oskuste kaardistamine.

### 2023-11-27

### 2023-12-1

### 2023-12-4

### 2023-12-8

### 2023-12-11

### 2023-12-15

### 2023-12-18

### 2023-12-22

### 2024-1-8

### 2024-1-12

### 2024-1-15

### 2024-1-19

Kinemaatika kahes dimensioonis ja vektorite teadmiste ja oskuste kaardistamine.

### 2024-1-22

## Kohila Gümnaasiumi Kalender

### 2023-09-04

Teaduse olemus.

Mudelid, teooriad ja seadused.

Kava:

1. Tutvustus.

2. Ajurünnak õpitu kohta.

3. Plickers: *Teaduse olemus*[@giancoli, lk 2-4].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni alguseni: Kui veel pole, siis soetada *A4*-vormingus ruuduline kaustik või sellised lehed ja köitja, et sinna luua konspekt. Kõik seekord ülestäheldatu sinna konspekti ümber kirjutada! Kui veel pole, siis ka soetada eri värvi füüsilised kirjutusvahendid ja geomeetriavahendid! Lugeda, vaadata ja kuulata üle kontaktsessioonis viidatud teave!

### 2023-09-08

Teaduse olemus.

Füüsika ja selle seos teiste valdkondadega.

Mudelid, teooriad ja seadused.

Eesmärgina õpilane oskab

1. selgitada mõisteid loodus, maailm ja vaatleja; hindab füüsika kohta teiste loodusteaduste seas ning
määratleb füüsika uurimisala;

2. määratleda looduse struktuuritasemete skeemil makro-, mikro- ja megamaailma ning nimetab nende
erinevusi;

3. selgitada loodusteadusliku meetodi olemust ja teab, et eksperimenditulemusi üldistades jõutakse
mudelini.

Õppesisu: Füüsika kui loodusteadus. Füüsika kui nähtavushorisonte edasi nihutav teadus. Mikro-, makro- ja
megamaailm. Loodusteaduslik meetod. Vaatlus, eksperiment, mudeli loomine. Mudeli järelduste kontroll
ning mudeli areng.

Kava:

1. Arutelu teaduse olemuse üle[@fsikaline, lk 3-5]. Mis on füüsika? Millised on teised loodusteadused? Milline tööriistade komplekt toetab kõiki teadusi?

2. Ajurünnak oma tulevikusoovide ja füüsikaseoste kohta[@giancoli, lk 4-5].

3. Plickers: *Mudelid, teooriad ja seadused*[@giancoli, lk 5].

4. Arutelu mudelite, teooriate ja seaduste üle[@loodusteaduslik].

5. Teaduste piiride kirjeldamine[@looduse, @mikro].

### 2023-09-11

Ühikud, standardid ja Le Système international d’unités (SI)[@giancoli, lk 8-11].

Ühikute teisendamine[@giancoli, lk 11-12].

Eesmärk: Õpilane teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid.

Õppesisu: Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI).

Põhimõisted:

mõõtühik
: füüsikalise suuruse konkreetne väärtus, mida kokkuleppeliselt kasutatakse sama suuruse teiste väärtuste  arvuliseks iseloomustamiseks[@fsikalised]

mõõtühikute süsteem
: kokkulepitud põhiühikute ning neist tuletatud ülejäänud mõõtühikute moodustatud kogum[@erinevad]

Kava:

0. *10.b*: Plickers: *Mudelid, teooriad ja seadused*.

1. Mudelid.

2. *Powers of Ten - Ultimate Zoom (micro-macro - Imax combined)*[@powers; @giancoli, lk 9-10].

3. Näidete esitamine põhjusliku seose kohta[@giancoli, lk 128].

4. Füüsika üldprintsiibid ja nende kehtivuse tõestamine[@teised].

5. Plickers: *Teaduse olemus* ning *Mudelid, teooriad ja seadused*.

6. Ühik[@mtmised, lk 7].

7. Mõõtühikute eesliidetega tutvumine[@mthikute; @giancoli, lk 10; @mdulint].

8. Harjutused mõõtühikute eesliidetega.

### 2023-09-15

Eesmärgina õpilane

5. mõistab mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevust;

Õppesisu: Mõõtesuurus ja mõõdetava suuruse väärtus.

Kava:

0. *10.b*: Plickers: *Mudelid, teooriad ja seadused*.

1. Ümardamine[@rounding].

2. Tüvenumbrid[@sigfigpdf; @significantfigurespdf; @physics, lk 4-6; @introduction; @rounding].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni vastavalt kava teemadele, kui jõudsime selle teema läbida: lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

\onecolumn

### 2023-09-18

Ühikud, standardid ja Le Système international d’unités (SI)[@giancoli, lk 8-11].

Ühikute teisendamine[@giancoli, lk 11-12].

Mõõtmine ja määramatus; tüvenumbrid[@giancoli, lk 5-8].

Eesmärgid:

1. Oskus põhjendada mõõteseaduse vajalikkust üldaktseptitavate mõõtmistulemuste saamiseks.

2. Mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevus on selge.

3. Õpilane teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid.

7. Õpilane teab, et korrektne mõõtetulemus sisaldab ka määramatust, ning kasutab mõõtmisega kaasnevat
mõõtemääramatust hinnates standardhälvet (ilmselt käsitleme standardhälvet hiljem).

Õppesisu: Mõõtmine ja mõõtetulemus. Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI). Mõõtesuurus ja mõõdetava suuruse väärtus. Mõõteriistad ja mõõtevahendid.
Mõõteseadus (ilmselt käsitleme hiljem). Mõõtemääramatus ning selle hindamine. Mõõtetulemuste analüüs.

Põhimõisted:

füüsikaline suurus
: füüsikalise objekti mõõdetav iseloomustaja[@fsikaline, lk 5]

mõõtühik
: füüsikalise suuruse konkreetne väärtus, mida kokkuleppeliselt kasutatakse sama suuruse teiste väärtuste  arvuliseks iseloomustamiseks[@fsikalised]

mõõtühikute süsteem
: kokkulepitud põhiühikute ning neist tuletatud ülejäänud mõõtühikute moodustatud kogum[@erinevad]

Kava:

2. Tüvenumbrite harjutamine[@significantfigurespdf, lk 2].

3. Ühikute teisendamine[@physics, lk 1, 9-10; @introduction_conversions; @haynes_2014_crc, lk 1-27-1-46; @erinevad; @mthikute; @conversions; @unit; @physics_151].

4. SI[@sipostera4pdf; @physics, lk 8-9; @bureau_1974_the; @rahvusvaheline; @nistsp_1247png; @a11].

5. Dimensionaalanalüüs[@physics, lk 14-15; @introduction_base_dimensions]. SI tuletatud ühikute dimensionaalanalüüs.

6. Tabavus, täpsus, veatüübid ja määramatus[@mgpg11pdf; @physics, lk 3-4, 6; @introduction_accuracy_precision; @mtmise_precision; @a12; @kella; @mtetulemus; @neli; @higgsi; @a; @giancoli, lk 5-6].

7. Toores hinnang[@physics, lk 11-13].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni: Lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

### 2023-09-22

Ühikud, standardid ja Le Système international d’unités (SI)[@giancoli, lk 8-11].

Ühikute teisendamine[@giancoli, lk 11-12].

Mõõtmine ja määramatus; tüvenumbrid[@giancoli, lk 5-8].

Eesmärgid:

3. Õpilane teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid.

Õppesisu: Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI).

Põhimõisted:

füüsikaline suurus
: füüsikalise objekti mõõdetav iseloomustaja[@fsikaline, lk 5]

mõõtühik
: füüsikalise suuruse konkreetne väärtus, mida kokkuleppeliselt kasutatakse sama suuruse teiste väärtuste  arvuliseks iseloomustamiseks[@fsikalised]

Kava:

3. Ühikute teisendamine[@physics, lk 10; @introduction_conversions; @haynes_2014_crc, lk 1-27-1-46; @erinevad; @mthikute; @conversions; @unit; @physics_151].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni: Lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

\twocolumn

### 2023-09-25

Ühikud, standardid ja Le Système international d’unités (SI)[@physics, lk 6-9].

Ühikute teisendamine[@physics, lk 10].

Mõõtmine ja määramatus; tüvenumbrid[@physics, lk 3-6].

Eesmärgid:

1. Oskus põhjendada mõõteseaduse vajalikkust üldaktseptitavate mõõtmistulemuste saamiseks.

2. Mõõdetava suuruse ja mõõtmistulemuse suuruse väärtuse erinevus on selge.

3. Õpilane teab ja oskab rakendada rahvusvahelise mõõtühikute süsteemi (SI) põhisuurusi ning nende mõõtühikuid.

7. Õpilane teab, et korrektne mõõtetulemus sisaldab ka määramatust, ning kasutab mõõtmisega kaasnevat
mõõtemääramatust hinnates standardhälvet (ilmselt käsitleme standardhälvet hiljem).

Õppesisu: Mõõtmine ja mõõtetulemus. Mõõtühikud
ja vastavate kokkulepete areng. Rahvusvaheline mõõtühikute süsteem (SI). Mõõtesuurus ja mõõdetava suuruse väärtus. Mõõteriistad ja mõõtevahendid.
Mõõteseadus (ilmselt käsitleme hiljem). Mõõtemääramatus ning selle hindamine. Mõõtetulemuste analüüs.

Põhimõisted:

füüsikaline suurus
: füüsikalise objekti mõõdetav iseloomustaja[@fsikaline, lk 5]

mõõtühik
: füüsikalise suuruse konkreetne väärtus, mida kokkuleppeliselt kasutatakse sama suuruse teiste väärtuste  arvuliseks iseloomustamiseks[@fsikalised]

mõõtühikute süsteem
: kokkulepitud põhiühikute ning neist tuletatud ülejäänud mõõtühikute moodustatud kogum[@erinevad]

Kava:

3. Ühikute teisendamine[@physics, lk 10; @introduction_conversions; @haynes_2014_crc, lk 1-27-1-46; @erinevad; @mthikute; @conversions; @unit; @physics_151]. *10a*: Alustame ülesandest *F*. *10b*: Jätkame *A4*-lehel olevate ühikute teisendamise ülesannete lahendamist.

4. SI[@sipostera4pdf; @physics, lk 8-9; @bureau_1974_the; @rahvusvaheline; @nistsp_1247png; @a11].

5. Dimensionaalanalüüs[@physics, lk 14-15; @introduction_base_dimensions]. SI tuletatud ühikute dimensionaalanalüüs.

6. Tabavus, täpsus, veatüübid ja määramatus[@mgpg11pdf; @physics, lk 3-4, 6; @introduction_accuracy_precision; @mtmise_precision; @a12; @kella; @mtetulemus; @neli; @higgsi; @a; @giancoli, lk 5-6].

7. Toores hinnang[@physics, lk 11-13].

Kontaktsessiooniväline teemakohane tegevus järgmise kontaktsessiooni päeva alguseni vastavalt kava teemadele, kui jõudsime selle teema läbida: Lahendada @physics, lk 16-18 järgmised ülesanded:

3, 4: 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,

5: 55, 57,

2, 6: 1, 3, 5, 7, 9, 11, 13,

7: 35, 37, 39, 41, 43, 45, 47, 49, 51, 53.

2-7: 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79.

Lisaks lugeda, vaada-kuulata kõik kontaktsessiooni kirjelduses viidatud allikad!

### 2023-09-29

Ühikute teisendamine.

### 2023-10-2

Suurusjärk: kiire hindamine.

### 2023-10-6

Mõõtmed ja mõõtmete analüüs.

### 2023-10-9

### 2023-10-13

Füüsika olemuse, mõõtmise ja hindamise teadmiste ja oskuste kaardistamine.

### 2023-10-16

### 2023-10-20

### 2023-10-30

### 2023-11-3

### 2023-11-6

### 2023-11-10

### 2023-11-13

### 2023-11-17

### 2023-11-20

### 2023-11-24

Liikumise kirjeldamise teadmiste ja oskuste kaardistamine.

### 2023-11-27

### 2023-12-1

### 2023-12-4

### 2023-12-8

### 2023-12-11

### 2023-12-15

### 2023-12-18

### 2023-12-22

### 2024-1-8

### 2024-1-12

### 2024-1-15

### 2024-1-19

Kinemaatika kahes dimensioonis ja vektorite teadmiste ja oskuste kaardistamine.

### 2024-1-22
